### ISSUE TITLE
Holding up/down arrow on output times doesn't give a smooth animation

### ISSUE THREAD

**Issue by mostlyAtNight** [lutraconsulting/qgis-crayfish-plugin#10]
When holding down the up/down arrow on the output times, the plugin should render each output step (animating) before attempting to render the next output time.  At present it will miss large chunks of results, leading to a rather dodgy animation.

**Comment by mostlyAtNight** [comment]
Does not seem to be the case in Linux but the issue is there in windows even for small models.

**Comment by PeterPetrik** [comment]
Rendering is done in QGIS, closing the ticket here, please reopen the ticket in QGIS bug tracker is it is still an issue.
