### ISSUE TITLE
Error installing Crayfish 2.1 - requires admin

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#106]
I needed admin abilities to download the library which then comes up with some 407 error. This didn't used to happen on our end but does now which is a bit of a pain. I was able to run it on admin and the update worked but when I swap back to my profile the library update seems to be profile specific. Not sure if this would be a barrier that you are interested in for users in my work situation.

**Comment by wonder-sk** [comment]
I would need some more details:
- do you use a proxy server?
- what happens if you try to download the library without admin privileges? an error message is shown?

**Comment by wonder-sk** [comment]
Seems to be a local problem.
