### ISSUE TITLE
Outputted avi format can't be played in Windows Media Player

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#110]
Problem with the ffmpeg flags probably.

**Comment by wonder-sk** [comment]
I cannot replicate the problem - created videos play fine in windows media player in my windows 8.1 installation. I would need:
- exported AVI file (a sample with few frames would be enough)
- version of windows affected

**Comment by saberraz** [comment]
Works fine in Windows 7.
