### ISSUE TITLE
Flag for emitting images when creating an animation

### ISSUE THREAD

**Issue by michelk** [lutraconsulting/qgis-crayfish-plugin#112]
It would be great, to have the opportunity to specify an output directory for the intermediate images. Then it would be  possible with ImageMagick to overlay other images (eg. cross-sections or discharge time series).

Thanks for the great plugin.

**Comment by saberraz** [comment]
Have you tried to overlay your images in QGIS print composer and save it as a print composer template (.qpt) (it will be static though). You can then point the crayfish animation generator to the qpt file.

**Comment by michelk** [comment]
Thanks for hint; I didn't know that `.qpt` is a print composer template. 

But with this method the overlayed  images couldn't be time-varying; and I do want eg cross-sections with time varying waterlevel (which I create with another tool). 

Since the `ffmeg` command failed on my machine, 

    fmpeg version 2.6.3-1+b1 Copyright (c) 2000-2015 the FFmpeg developers
      built with gcc 4.9.2 (Debian 4.9.2-17)
      configuration: --prefix=/usr --extra-version=1+b1 --build-suffix=-ffmpeg --toolchain=hardened --l    ibdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --enable-shared --  disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libxvid --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzvbi --enable-libzmq --enable-frei0r --enable-libx264 --enable-libsoxr --enable-openal --enable-libopencv --enable-libx265
      libavutil      54. 20.100 / 54. 20.100
      libavcodec     56. 26.100 / 56. 26.100
      libavformat    56. 25.101 / 56. 25.101
      libavdevice    56.  4.100 / 56.  4.100
      libavfilter     5. 11.102 /  5. 11.102
      libavresample   2.  1.  0 /  2.  1.  0
      libswscale      3.  1.101 /  3.  1.101
      libswresample   1.  1.100 /  1.  1.100
      libpostproc    53.  3.100 / 53.  3.100
        Input #0, image2, from '/tmp/crayfishQ_fEId/%03d.png':
          Duration: 00:00:23.40, start: 0.000000, bitrate: N/A
            Stream #0:0: Video: png, rgb24, 1920x1080 [SAR 3780:3780 DAR 16:9], 5 fps, 5 tbr, 5 tbn, 5 tbc
    Please use -b:a or -b:v, -b is ambiguous
    [NULL @ 0x1dbc3c0] Unable to find a suitable output format for '    /home/user/tmp'
    /home/user/tmp: Invalid argument
    ['ffmpeg', '-f', 'image2', '-framerate', '5', '-i', '/tmp/crayfishQ_fEId/%03d.png', '-vcodec', 'mpeg4', '-b',   '10000K', '-r', '5', '-y', u'/home/user/tmp']
 
I got the directory with images anyway and did the desired overlay.

I also noticed that image-filenames are written with `printf("%03d.png",f)`. With high output time resolution this causes an issue, when animating. The formatting string should be dynamic according to the number of output-files.
