### ISSUE TITLE
Installation problem on debian/ubuntu with hdf5

### ISSUE THREAD

**Issue by michelk** [lutraconsulting/qgis-crayfish-plugin#113]
On both platforms, debian and ubuntu, I encountered a problem with `hdf5` when trying to install the corelib.

I had to manually adjust the `corelib/Makefile`
with 

    INCPATH = ... -I/usr/include/hdf5/serial
    LIBS = ... -L/usr/lib/x86_64-linux-gnu/hdf5/serial

Then

```bash
cd corelib
make
cd ..
./install.py
```

worked fine.

**Comment by wonder-sk** [comment]
That's interesting - I also build on Ubuntu, without any problems. What versions of debian/ubuntu and hdf packages do you use?

**Comment by wonder-sk** [comment]
Ok so obviously the package layout of HDF5 changed:
- in ubuntu trusty (version 1.8.11):
  - include dir ```/usr/include```
  - library ```/usr/lib/x86_64-linux-gnu/libhdf5.so.7```
- in debian jessie / ubuntu vivid (version 1.8.13)
  - include dir ```/usr/include/hdf5/serial```
  - library ```/usr/lib/x86_64-linux-gnu/libhdf5_serial.so.8```

**Comment by michelk** [comment]
Great thanks. Now everything is just building fine.
