### ISSUE TITLE
Crayfish libraries for 32bit and 64bit versions are in the same folder

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#114]
If have QGIS 32 and 64 bit installed, every time I launch one, it overwrites the crayfish libs from the other one.
Maybe, better to keep each set of libs in one folder to avoid overwritting.

**Comment by PeterPetrik** [comment]
From Crayfish 3.x release and QGIS 3.4 release, the rendering and styling is implemented in QGIS Core. The data reading and support is implemented in [MDAL](https://github.com/lutraconsulting/MDAL/issues).
Please reopen the ticket in QGIS bug tracker for rendering issues or MDAL for format support issues. 
Thanks.
