### ISSUE TITLE
Reload Mesh

### ISSUE THREAD

**Issue by michelk** [lutraconsulting/qgis-crayfish-plugin#119]
Often I do the actual mesh editing in SMS; but the GIS-overlays in QGIS. 
It would be great, if I'm editing the mesh in SMS and save, pressing F5 (reload) in QGIS would reload the mesh.

EDIT: 
Instead of automatically reloading the mesh, based on file-change, I would prefer manually reloading, pressing F5.

As a workaround, one has to close and open the whole QGIS-Project.

**Comment by PeterPetrik** [comment]
From Crayfish 3.x release and QGIS 3.4 release, the rendering and styling is implemented in QGIS Core. The data reading and support is implemented in [MDAL](https://github.com/lutraconsulting/MDAL/issues).
Please reopen the ticket in QGIS bug tracker for rendering issues or MDAL for format support issues. 
Thanks.
