### ISSUE TITLE
Batch export to animation

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#120]
There are many animations to create, is there any way to create animations in batch mode using crayfish.
I have a qpt template for the maps. Also, we have many maps in which only the tuflow results will change. Is there any way to change the TUFLOW results and save animations in batch mode, even if it doesn’t use qpt template it will help us a lot?

**Comment by michelk** [comment]
+1

It would also be great, if flood maps could be processed in batch mode. I haven't even figured out how to  plot print-composers to png or pdf in batch mode.

**Comment by PeterPetrik** [comment]
should be added in the QGIS core processing algorithms, we no longer develop processing algs in the crayfish plugin.
