### ISSUE TITLE
Cryptic Proxy Server Errors

### ISSUE THREAD

**Issue by mostlyAtNight** [lutraconsulting/qgis-crayfish-plugin#121]
If a proxy server is required and the user has not set up their proxy server settings, error messages generated could be more useful.  

Suggest something like:

"Unfortuantely FIXME could not be downloaded. 

If your network requires the use of a proxy server (your IT support staff will know) you will need to input the relevant settings in QGIS > Settings > Network. The detailed error was:

..."

**Comment by PeterPetrik** [comment]
fixed in 2.4.0
