### ISSUE TITLE
libc6 problem in Debian

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#122]
when I try to run the Crayfish-plugin in QGIS (2.10) I get the following error:

"OSError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by ~/.qgis2/python/plugins/crayfish/libcrayfish.so.1)".
This is due to the glibc6 version 2.13 on my Debian Wheezy. Is it possible to link Crayfish against libc6 version 2.13 because there seem to be no libc6 > 2.13 in the Debian-repositories (stable and backport) for Debian Wheezy.

**Comment by saberraz** [comment]
Have you tried to compile it from source for your platform. The instructions are here:
https://github.com/lutraconsulting/qgis-crayfish-plugin under compiling section of Readme.

**Comment by PeterPetrik** [comment]
From Crayfish 3.x release and QGIS 3.4 release, the rendering and styling is implemented in QGIS Core. The data reading and support is implemented in [MDAL](https://github.com/lutraconsulting/MDAL/issues).
Please reopen the ticket in QGIS bug tracker for rendering issues or MDAL for format support issues. 
Thanks.
