### ISSUE TITLE
Add support for rotated canvas

### ISSUE THREAD

**Issue by strk** [lutraconsulting/qgis-crayfish-plugin#126]
Canvas rotation was introduced in qgis 2.8.
See http://hub.qgis.org/issues/11900

**Comment by PeterPetrik** [comment]
From Crayfish 3.x release and QGIS 3.4 release, the rendering and styling is implemented in QGIS Core. The data reading and support is implemented in [MDAL](https://github.com/lutraconsulting/MDAL/issues).
Please reopen the ticket in QGIS bug tracker for rendering issues or MDAL for format support issues. 
Thanks.
