### ISSUE TITLE
Add support for multi style for crayfish layer

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#129]
Currently, it is not possible to:
- Have multi-style assigned to a single Crayfish layer
- Copy and paste style from one layer to another

**Comment by PeterPetrik** [comment]
From Crayfish 3.x release and QGIS 3.4 release, the rendering and styling is implemented in QGIS Core. The data reading and support is implemented in [MDAL](https://github.com/lutraconsulting/MDAL/issues).
Please reopen the ticket in QGIS bug tracker for rendering issues or MDAL for format support issues. 
Thanks.
