### ISSUE TITLE
Large dataset support

### ISSUE THREAD

**Issue by mostlyAtNight** [lutraconsulting/qgis-crayfish-plugin#13]
Currently, Crayfish loads entire datasets into memory.  Very large layers result in a bad allocation.  

It would be better to load some of the dataset into memory and have functionality for loading the required output steps into memory automatically as required.

**Comment by PeterPetrik** [comment]
Data loading is done in [MDAL](https://github.com/lutraconsulting/MDAL/issues) for QGIS 3.4 release
