### ISSUE TITLE
Support for netcdf

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#139]
according to gdal and
http://www.unidata.ucar.edu/software/netcdf/

**Comment by PeterPetrik** [comment]
https://www.unidata.ucar.edu/software/netcdf/examples/files.html

**Comment by PeterPetrik** [comment]
http://www.gdal.org/frmt_netcdf.html

**Comment by PeterPetrik** [comment]
format is quite generic, but they have convensions 
http://ferret.wrc.noaa.gov/noaa_coop/coop_cdf_profile.html
http://cfconventions.org/cf-conventions/v1.6.0/cf-conventions.html

to "The conventions define metadata that provide a definitive description of what the data in each variable represents, and of the spatial and temporal properties of the data. This enables users of data from different sources to decide which quantities are comparable, and facilitates building applications with powerful extraction, regridding, and display capabilities."

**Comment by PeterPetrik** [comment]
official api for reading: https://github.com/Unidata/netcdf-c/tree/v4.4.0
it seems that GDAL reimplemented it on its own

**Comment by PeterPetrik** [comment]
This dataset shows relative humidity at multiple levels, daily averages for 2003 
https://www.unidata.ucar.edu/software/netcdf/examples/rhum.2003.nc
GDAL shows global metadata:
NETCDF_DIM_EXTRA={time,level}
NETCDF_DIM_level_DEF={8,5}
NETCDF_DIM_level_VALUES={1000,925,850,700,600,500,400,300}
NETCDF_DIM_time_DEF={365,6}
NETCDF_DIM_time_VALUES={....}
and every band has 
NETCDF_DIM_level=XXX
NETCDF_DIM_time=YYYY
