### ISSUE TITLE
Problem with -180 and 180 degrees data

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#143]
Some datasets are between -180 and 180 and hence not shown properly on the map.

**Comment by saberraz** [comment]
Regression in 2.3

**Comment by PeterPetrik** [comment]
@saberraz do you have data for this (are they publicly available?)

**Comment by saberraz** [comment]
http://www.ncl.ucar.edu/Applications/Data/cdf/ts_Amon_CESM1-CAM5_historical_r1i1p1_185001-200512.nc

**Comment by PeterPetrik** [comment]
From Crayfish 3.x release and QGIS 3.4 release, the rendering and styling is implemented in QGIS Core. The data reading and support is implemented in [MDAL](https://github.com/lutraconsulting/MDAL/issues).
Please reopen the ticket in QGIS bug tracker for rendering issues or MDAL for format support issues. 
Thanks.
