### ISSUE TITLE
add hec2d test

### ISSUE THREAD

**Issue by PeterPetrik** [lutraconsulting/qgis-crayfish-plugin#145]

**Comment by saberraz** [comment]
[test.p01.zip](https://github.com/lutraconsulting/qgis-crayfish-plugin/files/177381/test.p01.zip)
This file can be used for testing. But unfortunately, crayfish can't read it.

**Comment by erpas** [comment]
Being invited by Saber I would like to share [HEC-RAS example results with two 2D areas](https://github.com/erpas/qgis-crayfish-plugin/blob/master/test/data/baldeagle_multi2d.hdf) as a testing data.
