### ISSUE TITLE
Crayfish Library Not Found on Debian Jessie QGIS 2.14.1

### ISSUE THREAD

**Issue by ZedeN1** [lutraconsulting/qgis-crayfish-plugin#166]
_My system: Linux blackwater 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04) x86_64 GNU/Linux_

I have recently updated to QGIS 2.14.1 from 2.12. With the update I have started getting QGIS crashes when loading large TUFLOW .DAT or .XMDF results while using Crayfish 2.1.3. I updated to the newest version of crayfish but I keep getting the following errors on QGIS startup:
> "Crayfish depends on a platform specific compiled library which was not found. Would you like to attempt to automatically download and install one from the developer's website?"

Upon clicking yes I get the expected error:
> HTTP Error 404: Not Found

I have run the following command prior to installing:
`sudo apt-get install build-essential libqt4-dev qt4-qmake libgdal-dev libhdf5-dev libnetcdf-dev libproj-dev git`

For now have to revert back to using Crayfish 2.1.3 which works but not for large files.

**Comment by saberraz** [comment]
You need to check-out the repo and run the installer if you want to use the latest version.

https://github.com/lutraconsulting/qgis-crayfish-plugin/blob/master/README.md
`git clone https://github.com/lutraconsulting/qgis-crayfish-plugin.git`
and then
```
cd qgis-crayfish-plugin
./install.py
```

**Comment by ZedeN1** [comment]
My normal install procedure: download the zip from github, extract, CD to the dir and run ./install.py

I also tried got clone but that didn't help.

I am able to reinstall older versions of crayfish with no issues using the aforementioned zip method.

**Comment by saberraz** [comment]
I suggest to remove crayfish plugin from ~/.qgis2/python/plugins
And try to install again.

Either git clone or direct zip download should work.

**Comment by PeterPetrik** [comment]
Would it be possible @ZedeN1 to attach log (stdout/stderr) of the install.py script?

**Comment by ZedeN1** [comment]
Ok, did the following:

- Closed QGIS
- deleted /usermnt/pavel/.qgis2/python/plugins/crayfish
- `sudo apt-get install build-essential libqt4-dev qt4-qmake libgdal-dev libhdf5-dev libnetcdf-dev libproj-dev git`
- returned: `build-essential is already the newest version.
libgdal-dev is already the newest version.
git is already the newest version.
libhdf5-dev is already the newest version.
libnetcdf-dev is already the newest version.
libproj-dev is already the newest version.
libqt4-dev is already the newest version.
qt4-qmake is already the newest version.`
- downloaded brand new **qgis-crayfish-plugin-master.zip** from github
- extracted to qgis-crayfish-plugin-master
- opened terminal in /qgis-crayfish-plugin-master/
- did `$ ./install.py` _Terminal log is attached as [TerminalLog.txt](https://github.com/lutraconsulting/qgis-crayfish-plugin/files/217369/TerminalLog.txt)_
- Start QGIS 2.14.1-Essen and it gives me the "Crayfish depends on a platform specific compiled library which was not found. Would you like to attempt to automatically download and install one from the developer's website?" error.
- I have 2 crayfish menu options under Plugins-Crayfish, About and Upload to Illuvis. About shows Crayfish 2.2.0 **BUT** no crayfish button on 'Manage Layers Toolbar' and Upload to Illuvis menu option returns: 

> 2016-04-13T15:45:56	1	Traceback (most recent call last):
> 			  File "/usermnt/pavel/.qgis2/python/plugins/crayfish/plugin.py", line 415, in upload
> 			    d = upload_dialog.UploadDialog(self.iface, self.dock.currentCrayfishLayer())
> 			AttributeError: 'NoneType' object has no attribute 'currentCrayfishLayer'

- deleted /usermnt/pavel/.qgis2/python/plugins/crayfish
- tried `$ sudo ./install.py`, log attached as 
[SudoTerminalLog.txt](https://github.com/lutraconsulting/qgis-crayfish-plugin/files/217368/SudoTerminalLog.txt). This did **NOT** create a crayfish folder in /usermnt/pavel/.qgis2/python/plugins and therefore QGIS started without errors, but with no crayfish.
- did $./install.py followed by $ sudo ./install.py, it didnt help.
- deleted /usermnt/pavel/.qgis2/python/plugins/crayfish
- opened terminal in /qgis-crayfish-plugin-master/ for version **2.13**. _Terminal log attached as [2.1.3-TerminalLog.txt](https://github.com/lutraconsulting/qgis-crayfish-plugin/files/217370/2.1.3-TerminalLog.txt)_
- QGIS opens with no problems, I can see all the menu options under Plugins-Crayfish and Add Crayfish Layer button is visible. Still have problems opening very large .DAT files.

**Comment by PeterPetrik** [comment]
@ZedeN1 the problem occurs because you use QT5 and not QT4 for compilation of the crayfish. Please try to set environment variable 
`export QT_SELECT=qt4 `
test qt version by 
`qmake -v`
 and in clean folder recompile crayfilsh with ./install.py

**Comment by ZedeN1** [comment]
@PeterPetrik Thanks for your suggestion, worked like a charm! Had to re-extract the .zip but no errors on QGIS startup. Also fixed the crash opening large .DAT files :+1: 
Might be worth adding it to the readme?

**Comment by PeterPetrik** [comment]
I have already done that. Enjoy new version!
