### ISSUE TITLE
Add Processing modules

### ISSUE THREAD

**Issue by wonder-sk** [lutraconsulting/qgis-crayfish-plugin#168]
It would be good to add some Crayfish-related modules to Processing toolbox. In "tools" directory there are already scripts that could be ported:
- export nodes as point layer
- export elements as polygon layer
- export as interpolated raster grid

**Comment by PeterPetrik** [comment]
https://github.com/qgis/QGIS/tree/master/python/plugins/processing/algs/exampleprovider

**Comment by PeterPetrik** [comment]
done some investigation on 168_processing branch. Seems like 0.5-1 day work to convert all scripts we have.
