### ISSUE TITLE
Error initialising the plugin with QGIS 2.12 on Fedora 23

### ISSUE THREAD

**Issue by pwcazenave** [lutraconsulting/qgis-crayfish-plugin#169]
When enabling/loading the plugin with QGIS 2.12 on Fedora 23, I get the following error message:

`Crayfish depends on a platform specific compiled library which was not found. Would you like to attempt to automatically download and install one from the developer's website?`

I followed the compilation instructions (i.e. git clone, export QT and then run install.py) and everything seems to work OK. I had to adjust `install.py` at line 45 to use `qmake-qt4` instead of just using qmake as Fedora doesn't have a `qmake` command (well, it may, but I have qt4 and qt5 installed side-by-side). 

I get my crayfish plugin directory created in my QGIS plugins directory ($HOME/.qgis2/python/plugins/).

`ldd libcrayfish.so.1` yields no missing dynamic libraries, so I'm a bit stumped by the error message.

Any help would be appreciated.

**Comment by saberraz** [comment]
@pwcazenave could you attach the output of your install.py here?

**Comment by pwcazenave** [comment]
@saberraz attached my install.py log (after `make clean` in the `crayfish` directory.

[install.py.txt](https://github.com/lutraconsulting/qgis-crayfish-plugin/files/227874/install.py.txt)

**Comment by wonder-sk** [comment]
@pwcazenave Could you please try to open Python console in QGIS, type these commands and see what do you get?
```python
import crayfish.core
crayfish.core.load_library()
crayfish.core.plugin_version()
crayfish.core.library_version()
```

**Comment by pwcazenave** [comment]
`Python Console 
Use iface to access QGIS API interface or Type help(iface) for more info
>>> import crayfish.core
>>> crayfish.core.load_library()
>>> crayfish.core.plugin_version()
131584
>>> crayfish.core.library_version()
131584
`
OK. That's weird. It's working fine now. I guess recompiling (`make clean` followed by `install.py`) fixed it.

Thanks for the help!

**Comment by saberraz** [comment]
Would be great if you could add your notes to README/install.py for Fedora users.

**Comment by pwcazenave** [comment]
I'll add some notes, although I didn't actually have to install any dependencies as we have a custom install script for Fedora which installs a bunch of scientific and development tools by default. However, I'll do my best to track down what's required.

It may be that there's a patch needed to `install.py` too.

**Comment by pwcazenave** [comment]
Pull request submitted.
