### ISSUE TITLE
Support for Flo-2D files

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#172]
Crayfish currently does not support http://www.flo-2d.com/ file formats. WIll be good to add support for the outputs from this package.

**Comment by PeterPetrik** [comment]
Branch flo2d. Missing

 - [ ] Maximum velocities
 - [ ] Water level (water depth = water level - bed)

**Comment by wonder-sk** [comment]
Added in #194
