### ISSUE TITLE
Export to polygon contours

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#173]
A feature to allow users to export quantities as polygon area contours ESRI Shapefile, based on thier current color ramp.

The resultant shapefile should have a value with upper-lower range of the contour ramp in the attribute data.

**Comment by PeterPetrik** [comment]
- [ ] export areas (not lines)
 - [ ] styling of new layer, colors from colormap
 - [ ] fixed levels based on active color style vs interval

Optional
 - [ ] auto detection of the reasonable resolutions + interval (e.g. 1/4 of the smallest cell edge)

**Comment by PeterPetrik** [comment]
@wonder-sk please review
