### ISSUE TITLE
Load only selected quantities

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#175]
Some files (e.g. GRIBB, nc, xmdf) can contain multiple quantities. Currently, all the quantities are loaded by default.

Ideally, during the opening session, you should be able to choose the list of quantities you'd like to load in QGIS.

**Comment by PeterPetrik** [comment]
From Crayfish 3.x release and QGIS 3.4 release, the rendering and styling is implemented in QGIS Core. The data reading and support is implemented in [MDAL](https://github.com/lutraconsulting/MDAL/issues).
Please reopen the ticket in QGIS bug tracker for rendering issues or MDAL for format support issues. 
Thanks.
