### ISSUE TITLE
Max values for Hec RAS results

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#178]
When viewing RAS 2D results there isn't functionality to view maximum depths/velocities etc.

**Comment by erpas** [comment]
The test results file (baldeagle_multi2d.hdf) contains the maxima for two 2D flow areas:

* /Results/Unsteady/Output/Output Blocks/Base Output/Summary Output/2D Flow Areas/lower 
* /Results/Unsteady/Output/Output Blocks/Base Output/Summary Output/2D Flow Areas/upper

**Comment by PeterPetrik** [comment]
@wonder-sk Please review #PR 182
