### ISSUE TITLE
Cross-section plot may contain NaNs

### ISSUE THREAD

**Issue by wonder-sk** [lutraconsulting/qgis-crayfish-plugin#179]
If a line used for a cross-section plot is aligned with edges of mesh elements, for some points along the line the interpolation may fail and return NaN instead of interpolated value.

**Comment by wonder-sk** [comment]
![image](https://cloud.githubusercontent.com/assets/193367/14973951/7808da94-1121-11e6-883d-921caa7d8d40.png)

**Comment by PeterPetrik** [comment]
@wonder-sk Please review PR #181
