### ISSUE TITLE
Contours may not be fully rendered

### ISSUE THREAD

**Issue by wonder-sk** [lutraconsulting/qgis-crayfish-plugin#188]
Looks like a regression in 2.2

![image006](https://cloud.githubusercontent.com/assets/193367/15238063/b2ae0f56-1906-11e6-8225-e5229610e604.jpg)

**Comment by PeterPetrik** [comment]
Seems like sideeffect of https://github.com/lutraconsulting/qgis-crayfish-plugin/commit/8141e82b5ceeb20e7b12a469d7ab336ca2c7a1e9. Problem is that iszero() function uses tolerance 10e-5, but the mesh on this example is more fine.

**Comment by PeterPetrik** [comment]
see branch 188_contours. Extracted 2 mesh elements where problem exist.

**1e-4 iszero tolerance:**
![(2.2 iszero function: 1e-4](https://cloud.githubusercontent.com/assets/804608/15292216/4d76d9aa-1b82-11e6-826c-36ac5927e237.png)

**1e-8 iszero tolerance:**
![1-8](https://cloud.githubusercontent.com/assets/804608/15292235/64f8ab9e-1b82-11e6-9480-e0be656b17a7.png)

**1e-10
![1-10](https://cloud.githubusercontent.com/assets/804608/15292240/6be2258e-1b82-11e6-9c3f-2613352727a4.png)
 iszero tolerance:**

**Comment by PeterPetrik** [comment]
![0](https://cloud.githubusercontent.com/assets/804608/15313586/8c94ec46-1c0c-11e6-83ea-af591cee568c.png)
