### ISSUE TITLE
HEC-RAS velocities

### ISSUE THREAD

**Issue by erpas** [lutraconsulting/qgis-crayfish-plugin#189]
We currently present face perpendicular velocities (see negative values on profile below).

![selection_007](https://cloud.githubusercontent.com/assets/3106699/15239371/494c2ac6-18e2-11e6-98d5-b05b520694d3.png)

"Geometry/2D Flow Areas/Name/Faces NormalUnitVector and Length" part of HDF can be used to obtain velocity vector components.

**Comment by PeterPetrik** [comment]
From Crayfish 3.x release and QGIS 3.4 release, the rendering and styling is implemented in QGIS Core. The data reading and support is implemented in [MDAL](https://github.com/lutraconsulting/MDAL/issues).
Please reopen the ticket in QGIS bug tracker for rendering issues or MDAL for format support issues. 
Thanks.
