### ISSUE TITLE
Allow displaying time in the main canvas

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#190]
It will be good to view time as an annotation or label within the main QGIS canvas, similar to the export to animation, where user can define label, size, background, etc.

**Comment by PeterPetrik** [comment]
From Crayfish 3.x release and QGIS 3.4 release, the rendering and styling is implemented in QGIS Core. The data reading and support is implemented in [MDAL](https://github.com/lutraconsulting/MDAL/issues).
Please reopen the ticket in QGIS bug tracker for rendering issues or MDAL for format support issues. 
Thanks.
