### ISSUE TITLE
Hec RAS 1D results not shown

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#191]
It needs a bit of investigation as I am not familiar how 1D results are mapped. Maybe @erpas can shed some light?

**Comment by erpas** [comment]
HDF file contains 1D results in paths: 
1.Time series: /Results/Unsteady/Output/Output Blocks/Base Output/Unsteady Time Series/Cross Sections/
2. Maxima: /Results/Unsteady/Output/Output Blocks/Base Output/Summary Output/Cross Sections/

These are tables of WSEL, average velocity and flow for all cross-sections that are interpolated linearly on triangles spanned between the cross-sections and described in block: /Geometry/Cross Section Interpolation Surfaces/

So there are no ready-to-use maps. Mapping would require choosing a target raster resolution, probing a DTM for each cell inside the triangles, interpolation of WSEL and finally checking if WSEL > DTM.

**Comment by tstegman** [comment]
Greeting,

I am interested in mapping 1d and 2d results.  Is this possible to do in QGIS with Crayfish?  I understand the data is there and needs to be require some extra work.  Thanks for your time,  This functionality would be a huge plus!

**Comment by saberraz** [comment]
hi @tstegman currently Crayfish only supports 2D results from HEC-RAS. We will look into 1D results at some point in future. If you'd like to fund the work for 1D results, please contact us.

**Comment by RudyFrom3** [comment]
Hi Saber, I just emailed you an idea about a tool to burn 1D cross sections along a creek invert poly line....
(Are you aware of any tools outside of Hec-RAS that can do this ?)

**Comment by PeterPetrik** [comment]
From Crayfish 3.x release and QGIS 3.4 release, the rendering and styling is implemented in QGIS Core. The data reading and support is implemented in [MDAL](https://github.com/lutraconsulting/MDAL/issues).
Please reopen the ticket in QGIS bug tracker for rendering issues or MDAL for format support issues. 
Thanks.
