### ISSUE TITLE
Uncaught WindowsError: exception: access violation reading 0x0000000066E3A000


### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#192]
Steps to reproduce
1. Add an xmdf
2. Remove the xmdf
3. Add the same one

```
Traceback (most recent call last):
  File "C:/Users/Saber/.qgis2/python/plugins\crayfish\plugin.py", line 249, in addCrayfishLayer
    self.loadDatFile(inFileName)
  File "C:/Users/Saber/.qgis2/python/plugins\crayfish\plugin.py", line 352, in loadDatFile
    parentLayer.mesh.load_data( inFileName )
  File "C:/Users/Saber/.qgis2/python/plugins\crayfish\core.py", line 188, in load_data
    if not self.lib.CF_Mesh_loadDataSet(self.handle, path):
WindowsError: exception: access violation reading 0x0000000066E3A000

```

crayfish 2.2, QGIS 2.14.2-Essen on Windows 7

**Comment by PeterPetrik** [comment]
Unable to replicate on Linux

**Comment by PeterPetrik** [comment]
From Crayfish 3.x release and QGIS 3.4 release, the rendering and styling is implemented in QGIS Core. The data reading and support is implemented in [MDAL](https://github.com/lutraconsulting/MDAL/issues).
Please reopen the ticket in QGIS bug tracker for rendering issues or MDAL for format support issues. 
Thanks.
