### ISSUE TITLE
Crayfish layer missing from project file

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#193]
When opening a project with a crayfish layer, if the layer is missing, there is no option to point it to the new location/file.

**Comment by wonder-sk** [comment]
This would need to be supported by QGIS - to allow also plugins handle the situation with missing project files

**Comment by PeterPetrik** [comment]
From Crayfish 3.x release and QGIS 3.4 release, the rendering and styling is implemented in QGIS Core. The data reading and support is implemented in [MDAL](https://github.com/lutraconsulting/MDAL/issues).
Please reopen the ticket in QGIS bug tracker for rendering issues or MDAL for format support issues. 
Thanks.
