### ISSUE TITLE
SMS ASCII data: vectors not read supported

### ISSUE THREAD

**Issue by Doemelti** [lutraconsulting/qgis-crayfish-plugin#199]
As outlined in issue #67 SMS vector data is not yet supported in Crayfish. As a feature request I'd like to ask you to add support for this format.

**Comment by saberraz** [comment]
Do you have some sample data?

**Comment by saberraz** [comment]
Also is it not duplicate of #134 ?

**Comment by Doemelti** [comment]
I saw that issue too, but I'm not entirely sure it is the same issue. Please feel free to mark my request as duplicate if it is.

**Comment by saberraz** [comment]
Duplicate of #134
