### ISSUE TITLE
Handling maximums for AnuGA SWW files

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#202]
Currently, users need to run a script to extract maximums from SWW files. Would be good to have a nice method of extracting and displaying the maximums in Crayfish.

**Comment by PeterPetrik** [comment]
which script? If we have the script source, it would be easily possible to add a action on results dataset to "add Maximums". This action (in right click menu) can for example go through time-varying dataset and compute maximum and add it as a new CF layer.

**Comment by saberraz** [comment]
2 potential problems:
- Maximum values are not necessariliy the maximum values stored in the SWW file. For example, if the model outputs values every 300 seconds and the actual max happens in between the 300 seconds intervals, it will not be stored.
- It can take a long time to generate max values from SWW

IMO, AnuGA should store the max values in a seperate file or array so that it can be detected by crayfish upon loading.

**Comment by saberraz** [comment]
Here is the script:
https://github.com/GeoscienceAustralia/anuga_core/blob/5b3fe98861b2e9a91beb0cee21db68d8258a0bb9/anuga/file_conversion/sww2dem_new.py

and an example:
https://github.com/GeoscienceAustralia/anuga_core/blob/master/examples/cairns/export_results.py

**Comment by saberraz** [comment]
From the ANUGA developer's mail:

ANUGA has an operator anuga.operators.collect_max_quantities_operator which can be used to store the maximum at every timestep (not just sww output timesteps). 

For an example of its usage, see anuga_core/examples/cairns_excel/run_model.py

At the moment this operator only provides optional csv export of the maxima -- they don't go to netcdf.

**Comment by saberraz** [comment]
We have 2 options:

- Create a mesh and populate the csv values
- Create a geo-tiff

The first option is ideal as there will be no interpolation and the values are related to the native mesh element.

I still think it makes more sense to have it as a dummy time step within the netcdf result or as an external netcdf file. That's how majority of the modelling packages handle max values.

**Comment by PeterPetrik** [comment]
From Crayfish 3.x release and QGIS 3.4 release, the rendering and styling is implemented in QGIS Core. The data reading and support is implemented in [MDAL](https://github.com/lutraconsulting/MDAL/issues).
Please reopen the ticket in QGIS bug tracker for rendering issues or MDAL for format support issues. 
Thanks.
