### ISSUE TITLE
Problem with NC data

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#213]
NotImplementedError: QgsPluginLayer.writeStyle() is abstract and must be overridden

**Comment by saberraz** [comment]
It is in QGIS 2.15 master

**Comment by saberraz** [comment]
It is a problem with QGIS dock style

**Comment by wonder-sk** [comment]
Fixed in QGIS master in qgis/QGIS@8fcac87
