### ISSUE TITLE
Error with WRF nc data

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#214]
Crayfish: Invalid or missing data (NETCDF:"/home/ubuntu/projects/tmp/wrf/kat.nc":ISEEDARR_RAND_PERTURB).

Sample file can be downloaded from here:
http://www.enviroware.com/WRF_Browser/data/kat.nc

**Comment by cristoph15** [comment]
Sorry for a very late add (bump) is the new word. I have this file, that will not load into qgis 2.18 crayfish 2.4.0. It states " Invalid or missing data ". Any and all help is appreciated
. Test the file out. It may just be either my computer or my copy of qgis 2.18.


http://threddsbackup.ucar.edu/thredds/ncss/grib/NCEP/MRMS/Precip/MRMS_Precip_20170214_2000.grib2?var=PrecipFlag_altitude_above_msl&north=35.82&west=-104.5&east=-90.66&south=28.5&disableProjSubset=on&horizStride=1&time_start=2017-02-14T20%3A00%3A00Z&time_end=2017-02-14T20%3A58%3A00Z&timeStride=1&vertCoord=&accept=netcdf

**Comment by PeterPetrik** [comment]
From Crayfish 3.x release and QGIS 3.4 release, the rendering and styling is implemented in QGIS Core. The data reading and support is implemented in [MDAL](https://github.com/lutraconsulting/MDAL/issues).
Please reopen the ticket in QGIS bug tracker for rendering issues or MDAL for format support issues. 
Thanks.
