### ISSUE TITLE
Support for contour min/max from polyline

### ISSUE THREAD

**Issue by mostlyAtNight** [lutraconsulting/qgis-crayfish-plugin#22]
A feature that allows the user to create a new QGIS rubber-band (polyline) with which they draw a section in the canvas.  

Crayfish then looks at the values through the polyline and adjusts the countour options min/max values accordingly.

**Comment by PeterPetrik** [comment]
Export contours will be implemented in QGIS.

From Crayfish 3.x release and QGIS 3.4 release, the rendering and styling is implemented in QGIS Core. The data reading and support is implemented in [MDAL](https://github.com/lutraconsulting/MDAL/issues).
Please reopen the ticket in QGIS bug tracker for rendering issues or MDAL for format support issues. 
Thanks.
