### ISSUE TITLE
Mac build not working

### ISSUE THREAD

**Issue by PeterPetrik** [lutraconsulting/qgis-crayfish-plugin#220]
If dylib is used, it crashes QGIS when LoadLibrary() is called
If so is used, it LoadLibrary() returns unknown file type, first eight bytes, ....

**Comment by PeterPetrik** [comment]
https://github.com/lutraconsulting/qgis-crayfish-plugin#installing-crayfish-on-mac-os-experimental

**Comment by saberraz** [comment]
We also need to update the documentation

**Comment by PeterPetrik** [comment]
It is working now with QGIS3.3

From Crayfish 3.x release and QGIS 3.4 release, the rendering and styling is implemented in QGIS Core. The data reading and support is implemented in [MDAL](https://github.com/lutraconsulting/MDAL/issues).
Please reopen the ticket in QGIS bug tracker for rendering issues or MDAL for format support issues. 
Thanks.
