### ISSUE TITLE
Transparency for (range of) values

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#222]
Similar to rasters in QGIS, it will be great to have an option to set transparency level for specific values/range of values.

This will make the options for render below/above obsolete.

**Comment by PeterPetrik** [comment]
From Crayfish 3.x release and QGIS 3.4 release, the rendering and styling is implemented in QGIS Core. The data reading and support is implemented in [MDAL](https://github.com/lutraconsulting/MDAL/issues).
Please reopen the ticket in QGIS bug tracker for rendering issues or MDAL for format support issues. 
Thanks.
