### ISSUE TITLE
New FLO-2D OUT file structure

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#223]
Te plug in isn’t able to read the result files of the newer FLO-2D Version.
Apparently there’re some new lines added to the file structure now. 

Example files are availble on request.

**Comment by PeterPetrik** [comment]
It could be simply duplicate of #219. Crayfish is tested with FLO-2D PRO 16.02.14, where it works

**Comment by PeterPetrik** [comment]
Tested with master, it is duplicate of #219. closing
