### ISSUE TITLE
Improve installation of Crayfish support library

### ISSUE THREAD

**Issue by wonder-sk** [lutraconsulting/qgis-crayfish-plugin#225]
1. use message bar warning + a dialog with more details - instead of a series of message boxes
2. even if the support library is missing, load the GUI and just leave some bits of it disabled
3. in case of problems when loading the library, give an error message that is as precise as possible about what has failed
4. try to detect library versions (e.g. gdal, libc) to see if precompiled library is compatible

**Comment by PeterPetrik** [comment]
improved `rm -rf`!
