### ISSUE TITLE
Crayfish and Flo-2d Mesh Alignment

### ISSUE THREAD

**Issue by kaplanjc12** [lutraconsulting/qgis-crayfish-plugin#227]
The flo-2d grids and the crayfish mesh cells do not match. The crayfish numbers also do not match the grid numbers - ([grid#, x, y] in cadpts.dat).   Attached are example pictures and flo-2d files grid.shp, 
fplain.dat, and cadpts.dat. 

![mesh_grid differences](https://cloud.githubusercontent.com/assets/21102156/17789975/8a40e022-6562-11e6-8776-0de71d24cb85.png)
![crayfish_flo2dmeshcompare](https://cloud.githubusercontent.com/assets/21102156/17789976/8a58ae28-6562-11e6-8c89-5aef4893fd69.png)

[F2d.zip](https://github.com/lutraconsulting/qgis-crayfish-plugin/files/425852/F2d.zip)

**Comment by PeterPetrik** [comment]
"The crayfish numbers also do not match the grid numbers" -> this is OK, because crayfish numbers are number of elements ( from FPLAIN.DAT file). cadpts contains node numbers, which are not shown in crayfish.

**Comment by PeterPetrik** [comment]
@wonder-sk can you please review https://github.com/lutraconsulting/qgis-crayfish-plugin/pull/277 ?

Problem was that that CADPTS.DAT contains X,Y coordinates of the cell centers, but I thought that it contains node coordinates. Node coordinates/indexes are not stored anywhere and need to be calculated from cell_size and cell center coordinates.
