### ISSUE TITLE
Handling the DefaultProxy

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#230]
When user sets the proxy to Default, there is no need for the username, password, host and port:
https://github.com/lutraconsulting/qgis-crayfish-plugin/blob/master/crayfish/gui/install_helper.py#L130

There should be an option in the above section to handle the DefaultProxy different than other types which require authentication and host details.

The deafult proxy settings is passed from the OS and hence no need for the plugin to do extra stuff.

**Comment by PeterPetrik** [comment]
maybe helpful: http://stackoverflow.com/questions/23041066/setting-proxy-parameter-in-qgis-plugins-how-to

**Comment by wonder-sk** [comment]
It would be good to switch to QgsNetworkAccessManager
