### ISSUE TITLE
reload/delete dataset 

### ISSUE THREAD

**Issue by michelk** [lutraconsulting/qgis-crayfish-plugin#231]
Currently it is not possible to delete  single layers of basement-results (eg. run_nds_depth.sol) or to reload them.
 
It would be handy to right-click on the layer in the Crayfish/Quantities window to do that. Right now there is only an option to 'Export to Raster Grid', ...

**Comment by saberraz** [comment]
Hi @michelk this is probably duplication of #95?

**Comment by michelk** [comment]
Thanks for the hint @saberraz . I haven't seen that one.

Closing in favor of #95
