### ISSUE TITLE
Crayfish-plugin is broken in debian-unstable and fedora

### ISSUE THREAD

**Issue by michelk** [lutraconsulting/qgis-crayfish-plugin#233]
>  QtWebKit support has been removed from `python-qt4`.

This affects at least the linux-distributions [debian-unstable](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=828031) and [fedora](https://hub.qgis.org/issues/15237).

I'm not sure, if the Crayfish-plugin could replace `QtWebKit` by another library.

EDIT: 
The `QtWebKit` library is only used in the About-dialog; [disabling](https://github.com/michelk/qgis-crayfish-plugin/blob/qtwebkit/crayfish/plugin.py) it temporarily works-around the issue for now.

**Comment by PeterPetrik** [comment]
blocker on ubuntu 16.04 qgis-2.18.0
