### ISSUE TITLE
Feature Request:  Quantity properties

### ISSUE THREAD

**Issue by michelk** [lutraconsulting/qgis-crayfish-plugin#235]
There is a feature request for  deleting/reloading quantities/layers  (#95).

Besides that, it would be useful to have an option to rename quantities. This would come in handy, when comparing different scenarios  by a common attribute (e.g. depth).  

Currently those are listed twice (e.g. depth, depth).

**Comment by michelk** [comment]
Well, I just figured out, that by double clicking the quantity, it is actually possible to rename it. Nevertheless, it would be helpful to have a properties-dialog with e.g. file-name the quantity is based on.

**Comment by saberraz** [comment]
I think the overall right-click function should be improved both in the main QGIS layer tree and aslo Crayfish quantity tree to make them consistent with the right-click options in QGIS.

For the Crayfish layer:

- Rename
- Styles: to save and load styles
- Properties: to display some stats(min and max), source data, histogram, meta-data (data-type, etc)

**Comment by PeterPetrik** [comment]
From Crayfish 3.x release and QGIS 3.4 release, the rendering and styling is implemented in QGIS Core. The data reading and support is implemented in [MDAL](https://github.com/lutraconsulting/MDAL/issues).
Please reopen the ticket in QGIS bug tracker for rendering issues or MDAL for format support issues. 
Thanks.
