### ISSUE TITLE
Crayfish High RAM Usage

### ISSUE THREAD

**Issue by jocdiazmuic** [lutraconsulting/qgis-crayfish-plugin#237]
Dear Dev team,

Recently I've been having some troubles to load a big slf (opentelemac's selafin)  file in crayfish and got out of RAM.

Currently I have a workstation with 32gb of RAM , and gets almost full (31.5gb) trying to load a 22gb SLF (650k+ nodes with 1150+ frames) before freezing and making me to kill the Qgis 2.16+ process in a linux (ubuntu 14.04) distribution.

Other tools that supports slf files in QGIS load that specific file with relative ease (couple of min), maybe because they read only the necessary timesteps and not the whole file. 

Is there a way to reduce the needed RAM of crayfish (when loading slf files) or make some part of the load cache in a SSD/HDD?

Thank you so much for the awesome plugin!

**Comment by PeterPetrik** [comment]
From Crayfish 3.x release and QGIS 3.4 release, the rendering and styling is implemented in QGIS Core. The data reading and support is implemented in [MDAL](https://github.com/lutraconsulting/MDAL/issues).
Please reopen the ticket in QGIS bug tracker for rendering issues or MDAL for format support issues. 
Thanks.
