### ISSUE TITLE
Feature Request:  Display node and element attributes of meshes

### ISSUE THREAD

**Issue by michelk** [lutraconsulting/qgis-crayfish-plugin#239]
2DM- mesh files support arbitrary node (e.g. ID) and element (e.g. ID Material Index) attributes.

It would be very nice, if those could be displayed with the QGIS-'Identify Feature'-Tool.

**Comment by saberraz** [comment]
You can view the IDs as lables in Crayfish. But as you said, having the arbitrary attribute work with table manager and identify tool, will be a good idea.

In addition, will be good to have support for styling the mesh based on those values (e.g. creating thematic map of materials).

**Comment by saberraz** [comment]
Maybe a better option will be to export it as vector?

**Comment by PeterPetrik** [comment]
From Crayfish 3.x release and QGIS 3.4 release, the rendering and styling is implemented in QGIS Core. The data reading and support is implemented in [MDAL](https://github.com/lutraconsulting/MDAL/issues).
Please reopen the ticket in QGIS bug tracker for rendering issues or MDAL for format support issues. 
Thanks.
