### ISSUE TITLE
QGIS-Crayfish grib files not being showed  when imported.

### ISSUE THREAD

**Issue by cristoph15** [lutraconsulting/qgis-crayfish-plugin#243]
When I import the .grib files, they are not shown through crayfish.

**Comment by saberraz** [comment]
How do you open the files? Directly through QGIS add raster layer, or as a Crayfish layer?
Also, could you send me a link to your grib if it is publically available. Alternatively, feel free to send me the link privately

**Comment by cristoph15** [comment]
Sorry for the very late response. I have been very busy. I got the grib part working now. But .nc (netcdf files)  now do not show. I would add the layer through crayfish. I would choose what settings I want for this file. Then I let it download. It loads as a crayfish layer. But, it is not visible.  

http://threddsbackup.ucar.edu/thredds/ncss/grib/NCEP/NAM/CONUS_12km/NAM_CONUS_12km_20170101_1200.grib2/dataset.html

**Comment by saberraz** [comment]
Works fine with this [dataset](http://threddsbackup.ucar.edu/thredds/ncss/grib/NCEP/NAM/CONUS_12km/NAM_CONUS_12km_20170101_1200.grib2?var=Categorical_Freezing_Rain_surface&var=Reflectivity_height_above_ground&disableLLSubset=on&disableProjSubset=on&horizStride=1&time_start=2017-01-01T12%3A00%3A00Z&time_end=2017-01-05T00%3A00%3A00Z&timeStride=1&vertCoord=&accept=netcdf)

Could you link to your **NCSS Request URL:** at the bottom of the page?

**Comment by cristoph15** [comment]
Yes, I could. Here you go.http://threddsbackup.ucar.edu/thredds/ncss/grib/NCEP/NAM/CONUS_12km/NAM_CONUS_12km_20170101_1200.grib2?var=Temperature_height_above_ground&disableLLSubset=on&disableProjSubset=on&horizStride=1&time_start=2017-01-01T12%3A00%3A00Z&time_end=2017-01-05T00%3A00%3A00Z&timeStride=1&vertCoord=&accept=netcdf

 Thank you saberraz so much for helping me and continuing to!

**Comment by cristoph15** [comment]
I finally figured it out. I just had the wrong crs for the crayfish layer. Now it shows the files. Thanks for helping me saberraz. I really appreciated the help!

**Comment by cristoph15** [comment]
I finally figured it out. I just had the wrong crs for the crayfish layer. Now it shows the files. Thanks for helping me saberraz. I really appreciated the help!

**Comment by saberraz** [comment]
No problem. Glad it worked!
