### ISSUE TITLE
Support reading directory with multiple GDAL raster files (asc)

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#246]
A tool to convert a series of gdal rasters to a supported format. As an example, some models output results in form of TIF format with a time stamp (either in their name or as a meta data). A crayfish function to allow user to stitch the file to a supported format (e.g. netcdf, hdf, grib), will be great.

**Comment by PeterPetrik** [comment]
initial implementation on branch iss_246_rainfall

**Comment by saberraz** [comment]
Some minor bugs:
1- It reads only 10 of the rasters
2- It ignore the prj information
3- Timing is not populated correctly

TIF is another popular formats in gdal to parse.

**Comment by PeterPetrik** [comment]
we will support a directory with *.asc files. All files contains one raster band, that represents the data for one timestep. All files must represent the same geo-location. The time is read from the filename, where we expect filename:  <prefix><YYYYMMDD_HHMM><suffix>.asc
Vector datasets are not supported.

**Comment by PeterPetrik** [comment]
pending :https://github.com/lutraconsulting/qgis-crayfish-plugin/pull/295

**Comment by PeterPetrik** [comment]
@wonder-sk could you please have a look on the PR? thanks

**Comment by saberraz** [comment]
Would it be possible to add TIF for the file too? asc is a very out-dated format.

**Comment by saberraz** [comment]
In fact, TIF is supported. But you just need to add the extension to the list of supported formats...
I have renamed an asc to tif and Crayfish opened it.

**Comment by PeterPetrik** [comment]
added tif and tiff support (updated PR branch)

**Comment by PeterPetrik** [comment]
merged to master

**Comment by saberraz** [comment]
Problem with the Projection on the fly.
