### ISSUE TITLE
Problem with extracted datests from XMDF

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#250]
Often we post-process our TUFLOW results using the Utility res_to_res, for example to produce a difference between two xmdf flood results.

To save space, this process doesn’t create a 2dm, so you can end up with a xmdf that has a different name to the 2dm.

To load in SMS we simply create a copy of 2dm and rename it to match the xmdf and this works ok.

When I try to do the same thing within Crayfish I get the following error.:

Unable to load C:/Support/SEQWater/diff.xmdf

**Comment by PeterPetrik** [comment]
Fixed, added support for res_to_res utility results files to release 2.4
