### ISSUE TITLE
Make exported contours (as Areas) nicer

### ISSUE THREAD

**Issue by mach0** [lutraconsulting/qgis-crayfish-plugin#252]
If you export contours as areas right now they seem to be very different from the contours exported as lines.
Areas exactly follow the rastergrid which might not even be the correct result.
Line contours seem to follow the "real" height and produce much nicer output.
It would be nice to be able to produce the same output as with lines also with areas.

**Comment by PeterPetrik** [comment]
This is caused by different algorithms used. Problem is that one for lines cannot be used for polygons.

 - GDALContourGenerate
 - GDALFPolygonize

https://github.com/lutraconsulting/qgis-crayfish-plugin/blob/master/corelib/frmts/crayfish_gdal.cpp#L195-L224

**Comment by mach0** [comment]
So it's a case for GDAL/OGR request? Or do you see any chance of imlementing it in any other way inside the plugin?

**Comment by PeterPetrik** [comment]
both ways are probably possible...

**Comment by mach0** [comment]
Which one would be the most effective and sustainable solution?

**Comment by saberraz** [comment]
My prefered option woult be to use the following procedure:
1- Convert the CF layer to raster
2- Use GRASS r.reclass to classify the raster
3- Convert the reclassified raster to area vector



Here is an example of the Crayfish current output and the one I have done using GRASS reclassification (unfortunately my classes fall half-way through the CF values...but it should give you an idea of the quality of the output).

![cf_area_contour](https://cloud.githubusercontent.com/assets/2649047/22062943/279f2142-dd74-11e6-8201-755d781bcafd.png)

![classification_area_contour](https://cloud.githubusercontent.com/assets/2649047/22062950/308ac19e-dd74-11e6-96ee-99afc1e7921d.png)

**Comment by saberraz** [comment]
An option also s
![classification_area_contour_cleaned](https://cloud.githubusercontent.com/assets/2649047/22064827/355f9308-dd7d-11e6-8eb4-725c10b276a0.png)
hould be added to remove islands (v.clean rmarea=%area of feature, or a value)

**Comment by mach0** [comment]
both thumbs up also for v.clean rmarea=%area of feature, or a value
