### ISSUE TITLE
Allowing crayfish to read the data statistics from the headers or an external file

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#253]
Similar to gdal, it will be good to have a aux.xml to write/read crayfish layer stats. It helps with loading the right color profile and legend.

**Comment by PeterPetrik** [comment]
From Crayfish 3.x release and QGIS 3.4 release, the rendering and styling is implemented in QGIS Core. The data reading and support is implemented in [MDAL](https://github.com/lutraconsulting/MDAL/issues).
Please reopen the ticket in QGIS bug tracker for rendering issues or MDAL for format support issues. 
Thanks.
