### ISSUE TITLE
Add other quantities for FLO-2D

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#260]
Like Hazard, etc.

Also options to save snapshots.

**Comment by saberraz** [comment]
I assume it is part of summary.out of TIMDEP.HDF5 file.

**Comment by PeterPetrik** [comment]
@saberraz Min and Max arrays in TIMDEP.HDF5 files have dimensions 1xntimesteps . Hence it is unusable in crayfish. we would need nelementsx1 array to get maximum/minimum variable accross all timesteps?

**Comment by PeterPetrik** [comment]
From Crayfish 3.x release and QGIS 3.4 release, the rendering and styling is implemented in QGIS Core. The data reading and support is implemented in [MDAL](https://github.com/lutraconsulting/MDAL/issues).
Please reopen the ticket in QGIS bug tracker for rendering issues or MDAL for format support issues. 
Thanks.
