### ISSUE TITLE
Problem opening grib file

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#267]
It will come up with the following error and crashes QGIS:

An error has occurred while executing Python code: 

ValueError: None 
Traceback (most recent call last):
  File "/home/saber/.qgis2/python/plugins/crayfish/plugin_layer.py", line 775, in legendSymbologyItems
    dsC = self.currentContourDataSet()
  File "/home/saber/.qgis2/python/plugins/crayfish/plugin_layer.py", line 235, in currentContourDataSet
    return self.mesh.dataset(self.contour_ds_index)
  File "/home/saber/.qgis2/python/plugins/crayfish/core.py", line 267, in dataset
    return DataSet.from_handle(self.lib.CF_Mesh_dataSetAt(self.handle, index))
  File "/home/saber/.qgis2/python/plugins/crayfish/core.py", line 324, in from_handle
    return DataSet(handle)
  File "/home/saber/.qgis2/python/plugins/crayfish/core.py", line 331, in __init__
    raise ValueError(handle)
ValueError: None

**Comment by saberraz** [comment]
https://www.dropbox.com/s/lpgoympv7ud8sj2/_mars-atls06-95e2cf679cd58ee9b4db4dd119a05a8d-pTZ569.grib?dl=0

**Comment by saberraz** [comment]
This is a regression....works fine in 2.4 but not in 2.5

**Comment by PeterPetrik** [comment]
@saberraz do you have crayfish build from rel_2.5.0 branch?

**Comment by saberraz** [comment]
@PeterPetrik yes, that is correct...by 2.5 I meant the rel_2.5.0 branch

**Comment by PeterPetrik** [comment]
the "crash" part of the bug is fixed. But I am not sure why the latest gdal cannot open that particular dataset. It seems that it raises "Out of memory" error on reading timestep 13 from the dataset. And that error is basically "any error that comes from libgrib we show to user as out of memory, ... why not?" https://github.com/OSGeo/gdal/blob/trunk/gdal/frmts/grib/gribdataset.cpp#L328

**Comment by saberraz** [comment]
I build 2.4 with my gdal and report back. Ideally, the existing formats should be still supported with the new releases.

**Comment by PeterPetrik** [comment]
I have tested with multiple grib files and only this one shows the error. It is not that whole grib format is now not working.

**Comment by saberraz** [comment]
@PeterPetrik that is correct. Tested with other files and works fine.
