### ISSUE TITLE
Allow user to select render method of Element Outputs

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#271]
e.g. flow element centre velocity vector
![image](https://cloud.githubusercontent.com/assets/2649047/23016616/12ea3be8-f42f-11e6-90e0-0946b965f021.png)

**Comment by PeterPetrik** [comment]
Right now, Node quantities are rendered with contours (gradients), but element quantities are rendered by single value. This comes from the fact that we have a single value for whole element (cell -centered) in case of element output, but we have N-values for single element in case of node-outputs.

**Comment by PeterPetrik** [comment]
From Crayfish 3.x release and QGIS 3.4 release, the rendering and styling is implemented in QGIS Core. The data reading and support is implemented in [MDAL](https://github.com/lutraconsulting/MDAL/issues).
Please reopen the ticket in QGIS bug tracker for rendering issues or MDAL for format support issues. 
Thanks.
