### ISSUE TITLE
Export crayfish layer to kml

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#278]
KML supports time for rasters:
http://www.gdal.org/drv_libkml.html

**Comment by saberraz** [comment]
Here is more documentation on kml and time:
https://developers.google.com/kml/documentation/time

**Comment by PeterPetrik** [comment]
From Crayfish 3.x release and QGIS 3.4 release, the rendering and styling is implemented in QGIS Core. The data reading and support is implemented in [MDAL](https://github.com/lutraconsulting/MDAL/issues).
Please reopen the ticket in QGIS bug tracker for rendering issues or MDAL for format support issues. 
Thanks.
