### ISSUE TITLE
Export trace animation to .avi

### ISSUE THREAD

**Issue by PeterPetrik** [lutraconsulting/qgis-crayfish-plugin#280]
related to #102 

Export vector streamline/trace animation to avi

**Comment by johannesrohde** [comment]
Is there a time schedule for this enhancement?
I am really looking forward to it!

**Comment by PeterPetrik** [comment]
@johannesrohde it could be part of [crayfish-3,](http://www.lutraconsulting.co.uk/crowdfunding/qgis-crayfish-3/) but otherwise, there is no sponsor for this feature.

**Comment by PeterPetrik** [comment]
prerequisite is to implement trace animation in QGIS renderer first

**Comment by PeterPetrik** [comment]
fixed in https://github.com/lutraconsulting/qgis-crayfish-plugin/pull/413
