### ISSUE TITLE
OTF not working with the ECMWF data

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#283]
When adding grb/nc data from ECMWF, it is not possible to use OTF reprojection:

Here is an example dataset:
https://www.dropbox.com/s/tvczj9y4qyxbgjq/_mars-atls00-95e2cf679cd58ee9b4db4dd119a05a8d-YFwX6Z.grib?dl=0

If you try to add Google background map, it does not render the grb file at all.

**Comment by saberraz** [comment]
Also not with GDAL formats

**Comment by PeterPetrik** [comment]
From Crayfish 3.x release and QGIS 3.4 release, the rendering and styling is implemented in QGIS Core. The data reading and support is implemented in [MDAL](https://github.com/lutraconsulting/MDAL/issues).
Please reopen the ticket in QGIS bug tracker for rendering issues or MDAL for format support issues. 
Thanks.
