### ISSUE TITLE
Handling unknown CRS for Crayfish layers

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#285]
If user tries to load a CF layer with unknown projection it should be handled according to QGIS settings, i.e.:

- Prompt for CRS
- Use Project CRS
- Use Default CRS

Currently it applies no projection and it can be confusing. Here is an example:
https://www.dropbox.com/s/tvczj9y4qyxbgjq/_mars-atls00-95e2cf679cd58ee9b4db4dd119a05a8d-YFwX6Z.grib?dl=0

I set my QGIS to Prompt for CRS but Crayfish silently loads the layer without any CRS.

**Comment by PeterPetrik** [comment]
From Crayfish 3.x release and QGIS 3.4 release, the rendering and styling is implemented in QGIS Core. The data reading and support is implemented in [MDAL](https://github.com/lutraconsulting/MDAL/issues).
Please reopen the ticket in QGIS bug tracker for rendering issues or MDAL for format support issues. 
Thanks.
