### ISSUE TITLE
Not a big issue, but not all netcdf layers are supported on the QGIS crayfish on windows 7 64 bit qgis 2.16 3

### ISSUE THREAD

**Issue by cristoph15** [lutraconsulting/qgis-crayfish-plugin#293]
Here is my link and none of the variables are supported on the crayfish. I just though I should point that out and maybe someone might have a solution!

http://threddsbackup.ucar.edu/thredds/ncss/grib/NCEP/RAP/CONUS_40km/RR_CONUS_40km_20170406_2200.grib2?var=Total_snowfall_surface_Mixed_intervals_Accumulation&var=Total_precipitation_surface_Mixed_intervals_Accumulation&disableLLSubset=on&disableProjSubset=on&horizStride=1&time_start=2017-04-06T22%3A00%3A00Z&time_end=2017-04-07T16%3A00%3A00Z&timeStride=1&vertCoord=&accept=netcdf

**Comment by cristoph15** [comment]
I have not tried the new QGIS crayfish 5. Does it now support the file above?

**Comment by saberraz** [comment]
The link is no longer available. Could you update the link please?

**Comment by cristoph15** [comment]
NWS stopped hosting the link.

**Comment by cristoph15** [comment]
Actually, Nevermind. Here is the updated link. 

http://threddsbackup.ucar.edu/thredds/ncss/grib/NCEP/RAP/CONUS_40km/RR_CONUS_40km_20170428_1600.grib2?var=Frozen_Rain_surface_Mixed_intervals_Accumulation&var=Total_precipitation_surface_Mixed_intervals_Accumulation&var=Total_snowfall_surface_Mixed_intervals_Accumulation&north=48.99&west=-107.01&east=-95.94&south=35.91&disableProjSubset=on&horizStride=1&time_start=2017-04-28T16%3A00%3A00Z&time_end=2017-04-29T10%3A00%3A00Z&timeStride=1&vertCoord=&accept=netcdf

**Comment by saberraz** [comment]
@cristoph15 I can open the file in QGIS 2.18 in Linux. I think this is related to #257
