### ISSUE TITLE
Long list of formats

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#294]
Will be good to clean up the supported formats in the open crayfish dialog.
By default it should be "All supported formats".

And then the individual format (similar to Add Raster in QGIS)

![image](https://user-images.githubusercontent.com/2649047/26981971-bec81d56-4d2e-11e7-9fb0-66215eb04dc1.png)

**Comment by saberraz** [comment]
Here is the gdal format support example in QGIS:
![image](https://user-images.githubusercontent.com/2649047/27021683-e8796c80-4f41-11e7-86c3-3cfb6707ff1b.png)

**Comment by PeterPetrik** [comment]
Did in commit https://github.com/lutraconsulting/qgis-crayfish-plugin/pull/295/commits/5385f6364eee9c308a7ad1af47900b4c0a9e0adb on iss_246 branch (PR pending)

**Comment by saberraz** [comment]
looks fine to me

**Comment by PeterPetrik** [comment]
merged to master
