### ISSUE TITLE
MultipleTifsReader::parseBandInfo only treats files as <prefix><YYYYMMDD_HHMM><suffix>.*

### ISSUE THREAD

**Issue by stuartmead** [lutraconsulting/qgis-crayfish-plugin#298]
My files are not in the <prefix><YYYYMMDD_HHMM><suffix>.* format, but it wasn't triggering the parseBandInfo if statement starting at line 80 of [crayfish_tiffs](https://github.com/lutraconsulting/qgis-crayfish-plugin/blob/master/corelib/frmts/crayfish_tifs.cpp#L80). Basically, matches.length() will always equal 7 (I think because of how the regex is setup).

A solution is to replace line 80 with `if (!rx.exactMatch(fi.fileName())){` but the regex pattern could also be changed (ref. examples [here](http://doc.qt.io/qt-4.8/qregexp.html#matchedLength))

**Comment by saberraz** [comment]
@stuartmead do you want to do a PR based on your proposed changes?

**Comment by stuartmead** [comment]
Done, see #299.

**Comment by PeterPetrik** [comment]
@stuartmead Thank you for your PR, I have added a test and merged to the master.
