### ISSUE TITLE
Problem with crayfish v.2.6.1  when open QGIS 2.14.3 Essen WindowsError: [Error 126] 

### ISSUE THREAD

**Issue by simonecircosta** [lutraconsulting/qgis-crayfish-plugin#306]
Windows 7 Home Premium Service Pack 1

Hi,

when I start QGIS 2.14.3 Essen, the following message appears

![github_02](https://user-images.githubusercontent.com/32192917/30737510-324bdad8-9f87-11e7-9940-2d8e034e050e.JPG)

if i click the "yes" button, the following message appears

![github](https://user-images.githubusercontent.com/32192917/30737243-3598e16e-9f86-11e7-8503-8956abb911f6.JPG)
how i can fix this problem?

**Comment by saberraz** [comment]
@simonecircosta could you upgrade to the latest QGIS (2.18) and try again?

**Comment by simonecircosta** [comment]
I updated "QGIS" to the latest version (2.18) and the plugin is working properly

thank!
Simone
