### ISSUE TITLE
HYDRO_AS-2D Issues

### ISSUE THREAD

**Issue by johannesrohde** [lutraconsulting/qgis-crayfish-plugin#307]
Dear Lutra-Team,

i am very happy with your QGIS Plugin. I recently noticed some issues concerning importing HYDRO_AS-2D datafiles. Hopefully you could regard them in future releases.

dat files:
Changes in the Water-level datafiles (wspl.dat and wspl_max.dat, not in the rest of the dat-files):
Adjustment of the first Line form 'SCALAR' to 'SCALAR "NaN= 0.0000000E+00"'
(the Value of NaN might change if there are bed elevations below sea-level (<0))
At the moment, the line has to be adjusted manually before importing the files with Crayfish.

XMDF files for HYDRO_AS-2D:
Since Version 4.2 it is possible to store datafiles in XMDF-format (.h5) (equal to the Aquaveo-SMS XMDF-format).
The import with Crayfish doesn't work.
Maybe the HYDRO_AS-2D-XMDF-format differs from the XMDF-format which is supported in Crayfish?
I could send you small example files.

Greetings from Germany

**Comment by saberraz** [comment]
Hi @johannesrohde 
Many thanks for reporting the issues. A sample file will definitely help. Crayfish already supports SMS-XMDF format. It will be great if you could do a Pull Request for your format.

Otherwise, we are happy to look into the issue, if you become a supported customer.

Thanks

**Comment by johannesrohde** [comment]
Thank you for your quick reply and again for your great plugin!
I will discuss the possibility of becoming supported customer or doing a Pull Request with my coworkers and bosses.

For your information I attached an example of xmdf data files of hydro_as-2d.
[hydroas2dxmdfh5.zip](https://github.com/lutraconsulting/qgis-crayfish-plugin/files/1410037/hydroas2dxmdfh5.zip)
Cheers!

**Comment by saberraz** [comment]
@johannesrohde this will need crayfish user help:
http://www.lutraconsulting.co.uk/crowdfunding/qgis-crayfish-3/
