### ISSUE TITLE
Grid calculator gives INVALID syntax when working with UGRID nc files

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#313]
Files for testing is available.

**Comment by saberraz** [comment]
The grid calculator only handles "edges" and does not support "element2d".

**Comment by PeterPetrik** [comment]
From Crayfish 3.x release and QGIS 3.4 release, the rendering and styling is implemented in QGIS Core. The data reading and support is implemented in [MDAL](https://github.com/lutraconsulting/MDAL/issues).
Please reopen the ticket in QGIS bug tracker for rendering issues or MDAL for format support issues. 
Thanks.
