### ISSUE TITLE
Animation legend doesn't show up on default layout

### ISSUE THREAD

**Issue by scottjstoneman** [lutraconsulting/qgis-crayfish-plugin#315]
I recently put together a couple animations, but can’t seem to be able to have the legend show up in the “default layout”.  I was able to have a legend in the custom layout, but would prefer to use the default layout.  I am able to see the title and the time, but not the legend.  Is there anything I need to do in order to have the legend appear?  I have imported XMDF format time series from TUFLOW.

**Comment by saberraz** [comment]
Confirmed.
