### ISSUE TITLE
Error compiling in Arch Linux

### ISSUE THREAD

**Issue by samtux** [lutraconsulting/qgis-crayfish-plugin#317]
I get the next error compiling in Arch Linux x64:

`l -I. -isystem /usr/include/qt -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/qt/mkspecs/linux-g++ -o crayfish_capi.o crayfish_capi.cpp
crayfish_capi.cpp: In function 'void CF_Mesh_setSourceCrs(MeshH, const char*)':
crayfish_capi.cpp:362:31: error: 'fromAscii' is not a member of 'QString'
   mesh->setSourceCrs(QString::fromAscii(srcProj4));
                               ^~~~~~~~~
crayfish_capi.cpp: In function 'void CF_Mesh_setDestinationCrs(MeshH, const char*)':
crayfish_capi.cpp:367:36: error: 'fromAscii' is not a member of 'QString'
   mesh->setDestinationCrs(QString::fromAscii(destProj4));
                                    ^~~~~~~~~
crayfish_capi.cpp: In function 'bool CF_Mesh_calc_expression_is_valid(MeshH, const char*)':
crayfish_capi.cpp:382:28: error: 'fromAscii' is not a member of 'QString'
     QString exp = QString::fromAscii(expression);
                            ^~~~~~~~~
crayfish_capi.cpp: In function 'bool CF_Mesh_calc_derived_dataset(MeshH, const char*, float, float, double, double, double, double, bool, const char*)':
crayfish_capi.cpp:397:28: error: 'fromAscii' is not a member of 'QString'
     QString exp = QString::fromAscii(expression);
                            ^~~~~~~~~
crayfish_capi.cpp:398:35: error: 'fromAscii' is not a member of 'QString'
     QString outputFile = QString::fromAscii(output_filename);
                                   ^~~~~~~~~
crayfish_capi.cpp: In function 'void CF_RC_setParam(RendererConfigH, const char*, VariantH)':
crayfish_capi.cpp:430:24: error: 'fromAscii' is not a member of 'QString'
   QString k = QString::fromAscii(key);
                        ^~~~~~~~~
crayfish_capi.cpp: In function 'void CF_RC_getParam(RendererConfigH, const char*, VariantH)':
crayfish_capi.cpp:493:24: error: 'fromAscii' is not a member of 'QString'
   QString k = QString::fromAscii(key);
                        ^~~~~~~~~
make[1]: *** [Makefile:952: crayfish_capi.o] Error 1
make[1]: *** Waiting for unfinished jobs....
crayfish_mesh.cpp: In member function 'bool Mesh::reprojectMesh()':
crayfish_mesh.cpp:648:43: error: 'class QString' has no member named 'toAscii'
   projPJ projSrc = pj_init_plus(mSrcProj4.toAscii().data());
                                           ^~~~~~~
crayfish_mesh.cpp:656:44: error: 'class QString' has no member named 'toAscii'
   projPJ projDst = pj_init_plus(mDestProj4.toAscii().data());
                                            ^~~~~~~
make[1]: *** [Makefile:941: crayfish_mesh.o] Error 1
make[1]: Leaving directory '/home/samtux/Descargas/qgis-crayfish-plugin/corelib'
make: *** [Makefile:40: sub-corelib-make_default-ordered] Error 2`

**Comment by PeterPetrik** [comment]
Hi, make sure you use Qt4. Eg on ubuntu you need to `export QT_SELECT=qt4`.

**Comment by samtux** [comment]
Thank you  @PeterPetrik . I have been able to configure a plugin installation script for Arch Linux distribution. Available in the AUR package repository:

https://aur.archlinux.org/packages/qgis-crayfish-plugin/
