### ISSUE TITLE
export to grid doesnt support timesteps

### ISSUE THREAD

**Issue by mach0** [lutraconsulting/qgis-crayfish-plugin#319]

**Comment by saberraz** [comment]
It will be good to have a parameter for time here:
![image](https://user-images.githubusercontent.com/2649047/35155134-a06d15fe-fd24-11e7-83cc-a805d0dcfff5.png)

**Comment by saberraz** [comment]
Ideally, user should be able to select a time range as well as a single time step.

**Comment by PeterPetrik** [comment]
Export to grid will be part of QGIS. 

From Crayfish 3.x release and QGIS 3.4 release, the rendering and styling is implemented in QGIS Core. The data reading and support is implemented in [MDAL](https://github.com/lutraconsulting/MDAL/issues).
Please reopen the ticket in QGIS bug tracker for rendering issues or MDAL for format support issues. 
Thanks.
