### ISSUE TITLE
Gdal version doesn't work for export to contour

### ISSUE THREAD

**Issue by mach0** [lutraconsulting/qgis-crayfish-plugin#320]
I am using gdal 2.2.3 with my qgis and with latest crayfish it complains about wrong version.

**Comment by PeterPetrik** [comment]
From Crayfish 3.x release and QGIS 3.4 release, the rendering and styling is implemented in QGIS Core. The data reading and support is implemented in [MDAL](https://github.com/lutraconsulting/MDAL/issues).
Please reopen the ticket in QGIS bug tracker for rendering issues or MDAL for format support issues. 
Thanks.
