### ISSUE TITLE
Time format in default animation template

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#323]
The format of time was set when we did not have settings for time.

It is best to remove this option and leave it to user to set it in the main Crayfish panel.

**Comment by sklencar** [comment]
On a same branch as absolute time for animation export since its related.
(2.7.2/abs-time-animation)

**Comment by saberraz** [comment]
Time appears in wrong format everywhere in Crayfish Animation dialog and also exported avi.

This is in mesh properties:
![image](https://user-images.githubusercontent.com/2649047/72628303-eeca8d80-3945-11ea-8b23-1369fb527f7c.png)

And when I try it in Crayfish export to animation:
![image](https://user-images.githubusercontent.com/2649047/72628350-0ace2f00-3946-11ea-9329-117abeeb186e.png)

And the exported animation (this is only a frame):
![image](https://user-images.githubusercontent.com/2649047/72628393-246f7680-3946-11ea-8e7e-d709b484871d.png)

**Comment by PeterPetrik** [comment]
can you save you qgsproject , restart qgis and try again? I think that the dialog are updated only on the load time, the connection is not properly setup.

**Comment by saberraz** [comment]
Fixed in 3.2.1
