### ISSUE TITLE
HECRAS 2D timestep issues on import

### ISSUE THREAD

**Issue by KateEng** [lutraconsulting/qgis-crayfish-plugin#336]
When importing the 2D HDF file, the timestep seems to contain errors. instead of being import as a 4 day event, it is coming in as a 4 hour event, no errors within HECRAS with the model however. 
Does anyone know if this is a crayfish coding error?
Thanks, Kate

**Comment by PeterPetrik** [comment]
Hi Kate,
do you have a small example file you can share with us to be able to see the problem? Feel free to write to info@lutraconsulting.co.uk for more information.
Peter

**Comment by PeterPetrik** [comment]
From Crayfish 3.x release and QGIS 3.4 release, the rendering and styling is implemented in QGIS Core. The data reading and support is implemented in [MDAL](https://github.com/lutraconsulting/MDAL/issues).
Please reopen the ticket in QGIS bug tracker for rendering issues or MDAL for format support issues. 
Thanks.
