### ISSUE TITLE
Problem with mesh calculator when loading layers from an existing project

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#339]
To reproduce the error:
1- Load a crayfish layer
2- Save the project
3- Close QGIS
4- Open QGIS and load the project
5- Try to do a mesh calc
6- Invalid syntax when using some quantities

Loading the same CF layer, in a QGIS from scratch works with the same syntax

**Comment by PeterPetrik** [comment]
From Crayfish 3.x release and QGIS 3.4 release, the rendering and styling is implemented in QGIS Core. The data reading and support is implemented in [MDAL](https://github.com/lutraconsulting/MDAL/issues).
Please reopen the ticket in QGIS bug tracker for rendering issues or MDAL for format support issues. 
Thanks.
