### ISSUE TITLE
Expression to create inundation time

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#340]
Is it possible to write a syntax to generate start, peak and end time/duration when certain quantity appears in a cell?

**Comment by PeterPetrik** [comment]
From Crayfish 3.x release and QGIS 3.4 release, the rendering and styling is implemented in QGIS Core. The data reading and support is implemented in [MDAL](https://github.com/lutraconsulting/MDAL/issues).
Please reopen the ticket in QGIS bug tracker for rendering issues or MDAL for format support issues. 
Thanks.
