### ISSUE TITLE
Timesteps of multiple quantities of one CF layer are not sychronized

### ISSUE THREAD

**Issue by jamaa** [lutraconsulting/qgis-crayfish-plugin#342]
I have a crayfish layer loaded from a 2dm-file (containing the mesh) and then load multiple datasets (dat-files) into that crayfish layer as additional quantities (e.g. water level, water depth, flow velocities). Each dataset has multiple timesteps (which are identical across datasets, though).
I then "unlock" rendering to one dataset so that I can visualize water depths and flow velocities (two different quantities) at the same time.
Now, when I navigate through time using the slider or the buttons, this only affects the currently selected quantity, the other quantities either remain at their current timestep or sometimes even jump back to the first timestep. 
Additionally, after switching to a different quantity, the time slider display seems messed up, as the slider remains at the previously set position but the drop-down box displays a different time.

I expect the time slider to affect all quantities at the same time, i.e. for them to be synchronized.

**Comment by PeterPetrik** [comment]
From Crayfish 3.x release and QGIS 3.4 release, the rendering and styling is implemented in QGIS Core. The data reading and support is implemented in [MDAL](https://github.com/lutraconsulting/MDAL/issues).
Please reopen the ticket in QGIS bug tracker for rendering issues or MDAL for format support issues. 
Thanks.
