### ISSUE TITLE
crayfish 3d

### ISSUE THREAD

**Issue by michelk** [lutraconsulting/qgis-crayfish-plugin#344]
Hi,
I'm a bit confused, if a compatible version of crayfish plugin is available for QGIS 3.2. 

The  [homepage](https://www.lutraconsulting.co.uk/crowdfunding/qgis-crayfish-3/#support)  states, that the funding is completed. Has that  already been implemented? Is there a github branch to use?

Thanks, Michel

**Comment by saberraz** [comment]
Hi, this is now being implemented in the main QGIS through "mesh layer" or "mdal":
https://github.com/qgis/QGIS-Enhancement-Proposals/issues/119
https://github.com/lutraconsulting/MDAL

And here are some demos:
https://twitter.com/lutraconsulting/status/989075688228519939
https://twitter.com/lutraconsulting/status/996347616005943296

Contact us, if you would like to know the plan and want to sponsor a specific format.
