### ISSUE TITLE
Cannot export grid with resolution higher than 0.25 degrees

### ISSUE THREAD

**Issue by asierrl** [lutraconsulting/qgis-crayfish-plugin#348]
I have created an aggregated average of several time-bands and now I cannot export them. When I try from the Crayfish TOC (by right-clicking) I am not allowed to export with resolution higher than 0.25 degrees (I have a 4326 WGS84 lat long CRS), despite the data being in a 0.1 degrees resolution. It works well with 0.25 degrees.
If I try from the geoprocessing tools, I am not allowed to enter decimals in the resolution box. I even tried with a resolution of 1 from the geoprocessing tools box, but I systematically get an error Unable to load mesh (same when trying to Export contous). 
Best regards,
Asier

**Comment by saberraz** [comment]
Confirmed

**Comment by PeterPetrik** [comment]
Export to grid will be part of QGIS (not implemented yet).

From Crayfish 3.x release and QGIS 3.4 release, the rendering and styling is implemented in QGIS Core. The data reading and support is implemented in [MDAL](https://github.com/lutraconsulting/MDAL/issues).
Please reopen the ticket in QGIS bug tracker for rendering issues or MDAL for format support issues. 
Thanks.
