### ISSUE TITLE
Triangular mesh generation

### ISSUE THREAD

**Issue by michelk** [lutraconsulting/qgis-crayfish-plugin#35]
Are there other people, interested in triangular mesh generation within QGIS? 

I have been thinking about this for while. But I'm not sure if it is feasible.
I also don't know if QGIS is capable to provide similar functionality as for
example
[SMS](http://www.aquaveo.com/software/sms-surface-water-modeling-system-introduction).

**Comment by PeterPetrik** [comment]
Triangular mesh is generated automatically in QGIS rendering now. 

From Crayfish 3.x release and QGIS 3.4 release, the rendering and styling is implemented in QGIS Core. The data reading and support is implemented in [MDAL](https://github.com/lutraconsulting/MDAL/issues).
Please reopen the ticket in QGIS bug tracker for rendering issues or MDAL for format support issues. 
Thanks.
