### ISSUE TITLE
Feature requests: Basics in QGIS 3.4+

### ISSUE THREAD

**Issue by ZedeN1** [lutraconsulting/qgis-crayfish-plugin#354]
These are a few major features that are missing in new 3.4+ Crayfish compared to 2.18.x.
- At the moment there is no way to mouse over a cell and display the value of the cell. Value tool does not display the mesh elevations. In QGIS 2.18 it was shown below the "Display Mesh" tickbox.
![image](https://user-images.githubusercontent.com/18440960/48080415-7e729900-e1e5-11e8-9ceb-0840480de9b4.png)
- Add the Time Display Options from crayfish 2.18.x
![image](https://user-images.githubusercontent.com/18440960/48080754-5b94b480-e1e6-11e8-91e2-d53ce892630a.png)
- Display maximums in .DAT file.

Some other nice to haves:
- Add a dataset and automatically add the corresponding .2dm file.
- Add multiple extra datasets instead of adding them 1 by 1.
- Ability to change the default display style. At the moment it always switches on the "Native Mesh Rendering" and switches off the contours. In addition be able to change the default color ramp.
- Set the tolerances in the contours "Interpolation" for "Exact" method. At the moment it is very exact, letting it be rounded off to user defined decimal places / significant figures would make it usefull for high precision datasets.
- Profile tool no longer works with Crayfish / QGIS meshing.
- Crayfish plot doesn't seem to work for cross-sections or time-series, basically doesn't do anything.
- Crayfish plot is not able to plot cross-sections from other rasters, and since profile tool doesn't work, it is impossible to make profiles as shown in the image (QGIS 2.18, blue is .DAT file, red is .FLT)
![selection_121](https://user-images.githubusercontent.com/18440960/48080147-ef658100-e1e4-11e8-9781-f2d58aec69b8.png)

Could provide additional info/examples if needed. 
Thanks for your continued support!!

Edit:
Crayfish version 3.0.0
QGIS About:
![image](https://user-images.githubusercontent.com/18440960/48081461-09ed2980-e1e8-11e8-9ccd-8b795dbad47f.png)

**Comment by ZedeN1** [comment]
Thanks @saberraz, I will open them later.
Also, am I missing something or mesh layers can not be used as an elevation source in 3D Map view?

**Comment by saberraz** [comment]
Support for mesh layers in 3D is not possible yet. Again, we need funding  and we can do pretty much anything :)

**Comment by PeterPetrik** [comment]
- identify is implemented in QGIS 3.6
- 3d for meshes (frames) is in QGIS 3.6

Closing this issue, @ZedeN1 can you open one ticket for one enhancement/bug please?
