### ISSUE TITLE
Export mesh&datasets to vector format

### ISSUE THREAD

**Issue by PeterPetrik** [lutraconsulting/qgis-crayfish-plugin#356]
We need to add processing algorithm in crayfish plugin to be able to export raw MDAL data to geopackage.

MDAL supports data defined on vertices and faces (https://github.com/qgis/QGIS-Enhancement-Proposals/issues/119). Also it defines scalar data and vector data (x,y). 

relevant docs: https://github.com/qgis/QGIS/blob/master/src/core/mesh/qgsmeshlayer.h
https://github.com/qgis/QGIS/blob/master/src/core/mesh/qgsmeshdataprovider.h

test data: https://github.com/lutraconsulting/MDAL/tree/master/tests (2dm + ascii_dat) 

a) For face datasets, one feature in the vector layer will be one face. Attributes of the face will be dataset values in particular timestep, e.g. let say we have dataset "Depth" and "Velocity" 
so attributes will be
Depth = 1
Velocity_x = 1.0
Velocity_y = 2.0
....

b) for vertex datasets, the attributes will be the same, but the exported features will be nodes (vertices)

note: user will be able to export just one (selected timestep!). If one wants to export more/all, best to run this algorithm in batch mode.  Note that some datasets have just 1 value (e.g. Depth/Maximums). in this case it does not matter which timestep user selects, it is always exported

-------
As for graphical side, one will be able to select 
- INPUT: mesh layer
- INPUT: dataset groups (multichoice, ideally "all/none" button)
- INPUT: a timestep (combo box)
and 
- OUTPUT: geopackage filename where to put export or "in-memory" option 

the input/output UX should be in-line with most used processing algorithms so user knows where to click. 

-----

```
m = iface.activeLayer()
dp = m.dataProvider()
dp
<qgis._core.QgsMeshDataProvider object at 0x12d194678>
mesh = QgsMesh()
dp.populateMesh(mesh)
mesh.faceCount()
1600
mesh.face(0)
[34, 33, 0, 1]
mesh.vertexCount()
1683
mesh.vertex(0)
<QgsPoint: PointZ (20 10 0)>
dp.datasetGroupCount()
1
groupMeta = dp.datasetGroupMetadata(0)
groupMeta.isScalar()
False
dp.datasetCount(QgsMeshDatasetIndex(0))
27
values = dp.datasetValues(QgsMeshDatasetIndex(0, 2), 0, 300)
value = values.value(0)
value
<qgis._core.QgsMeshDatasetValue object at 0x12d194948>
value.x()
nan
value.y()
nan
```

**Comment by saberraz** [comment]
@marcel-dancak a minor GUI changes, the "Input vector layer" should be "Input mesh layer"
![image](https://user-images.githubusercontent.com/2649047/50953841-88966980-14ac-11e9-8ac2-a927117e85d7.png)
