### ISSUE TITLE
Can't export to animation

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#359]
I am using QGIS master and the latest Crayfish. But when I try to export a netcdf as animation, it asks me to select a time variable mesh

**Comment by saberraz** [comment]
Also same with grib files.

**Comment by saberraz** [comment]
Here is an example file:
https://issues.qgis.org/attachments/download/14085/Sapmple-file-for-QGIS.nc

**Comment by PeterPetrik** [comment]
fixed on master
