### ISSUE TITLE
crayfish 2.7.2 wont load

### ISSUE THREAD

**Issue by AGBNE** [lutraconsulting/qgis-crayfish-plugin#363]
Trying to load Crayfish for Qgis2.18. Plugin repository loads version 2.7.2 of crayfish. I get this error:

![capture](https://user-images.githubusercontent.com/46516104/51015496-36db0580-15b8-11e9-88ba-3f9ba1264f93.jpg)

**Comment by PeterPetrik** [comment]
qgis 2.x is not longer supported
