### ISSUE TITLE
Export vectors to points

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#370]
a processing alg to export vector components to points:

- a column containing magnitude
- a column containing direction
- an option for alg for the re-sampling of the output points

**Comment by saberraz** [comment]
User should be able to export the raw data (as they are presented in the file, e.g. on corners of an unstructured mesh) or on regular grid (e.g. 10m x 10m).

**Comment by PeterPetrik** [comment]
![Screenshot 2020-02-07 at 13 32 54](https://user-images.githubusercontent.com/804608/74030044-5ce6fb00-49ae-11ea-904b-a6f1883e53c5.png)

@saberraz export mesh vertices/export mesh faces processing alg of Crayfish can already export magnitude, velocity_x, velocity_y for ORIGINAL data location

so here you want to export both vector defined on faces or vertices on either original location or user grid?

**Comment by PeterPetrik** [comment]
question:? isnt it same as crayfish>rasterize following by raster>Raster pixels to points ...

**Comment by saberraz** [comment]
> I suggest to create new algorithm
> "Export data for user defined grid" where you can select all datasets (either raster or vector) and grid parameters (e.g. 10x10) and you got exported data [x, y] coords, magnitude, x_vector, y_vector

This sounds a good approach.

> question:? isnt it same as crayfish>rasterize following by raster>Raster pixels to points ...
I guess so, but the question is, whether it respects user-defined grids during the export?

**Comment by PeterPetrik** [comment]
- so you specifically do not need direction x-part and y-part is OK?

**Comment by saberraz** [comment]
To implement this feature, we need:
1- To improve the existing Export mesh vertices to have options to output direction (angle), x_component and y_component as additional attribute values.
2- A new processing algorithm to output mesh vertices at re-sampled locations (user-defined grids).
