### ISSUE TITLE
Rasterize timestep selection

### ISSUE THREAD

**Issue by kastepha** [lutraconsulting/qgis-crayfish-plugin#375]
There's an issue concerning the output timestep selection of the Rasterize tool in Crayfish 3.1.0. The exported raster contains results of a different timestep than selected. Here is an exemplary dataset of BASMENT 2.8 solution files:
[example files (2dm, sol)](https://polybox.ethz.ch/index.php/s/bQ3g5d7IfD97dhH)

**Comment by saberraz** [comment]
It appears to be selecting the first time step all the time.
