### ISSUE TITLE
Export Animation Error "Please activate contours or vector rendering ..."

### ISSUE THREAD

**Issue by prasunkgupta** [lutraconsulting/qgis-crayfish-plugin#387]
Win 10, QGIS 3.6.0 (both 64 bit)
Crayfish plugin v3.0.0

Test File: [Atlantic_Sept2017.nc](https://drive.google.com/open?id=1Zz58nUwX_pn9RpOrhudN5T2Y1e2rH_Fu)

Steps to reproduce:
1. Load the file as Mesh layer
2. Show Contours
3. Show Vectors
4. Right click on layer name and click on "Export Animation".

Output:
No animation
Error pop-up saying "Please activate contours or vector rendering and time-varying dataset for animation export"

![image](https://user-images.githubusercontent.com/7839690/54262460-36e58a80-4594-11e9-9743-92cd05ce9e38.png)

Am I missing something? Any help would be greatly appreciated.
Cheers

**Comment by PeterPetrik** [comment]
can you please update to latest crayfish version 3.1.2 are retest?

**Comment by prasunkgupta** [comment]
Resolved.
Updated plugin to 3.1.2
The error does not appear.
Able to generate the video.
Thank you @PeterPetrik
