### ISSUE TITLE
SAGA flow direction to GRIB tool: file extension not working anymore

### ISSUE THREAD

**Issue by jvdkwast** [lutraconsulting/qgis-crayfish-plugin#389]
In QGIS 3.6.0 it worked well to save the SAGA flow direction output to grib format by renaming the extension in the dialogue of the tool (https://youtu.be/qN_UC0AZhVM). This doesn't work anymore in 3.6.2, probably because of checking of accepted GDAL extensions. It would be better that the tool forces to give the .grb extension.

**Comment by PeterPetrik** [comment]
@jvdkwast do you have some input file for testing the algorithm ?

**Comment by jvdkwast** [comment]
Here's an input file:
[Flow_direction.zip](https://github.com/lutraconsulting/qgis-crayfish-plugin/files/3152398/Flow_direction.zip)

**Comment by PeterPetrik** [comment]
@jvdkwast I am not able to open that one, it says unrecognized GDAL input source. Do you have some in tif or other format?

**Comment by jvdkwast** [comment]
Sorry, the .sgrd file was missing. We should use this SAGA format, because that's the input that the tool should expect (i.e. output of SAGA processing tool for flow direction). Here's the new zipfile:
[Flow_direction2.zip](https://github.com/lutraconsulting/qgis-crayfish-plugin/files/3152583/Flow_direction2.zip)

**Comment by PeterPetrik** [comment]
fixed and released in Crayfish 3.1.3

**Comment by etiennethomassen** [comment]
This seems to have resurfaced for me in QGIS 3.12 (crayfish 3.2.1). 
Using @jvdkwast his file I only get raster files.

Using this file with it's given crs I actually get two files one .grb.tif and one .grb, besides a .grd.aux. But QGIS handles them both as raster. Tehy are almost equal size

**Comment by saberraz** [comment]
@etiennethomassen have you tried to add the grib file as Mesh?

**Comment by etiennethomassen** [comment]
Sorry been busy with lots of other stuff. But I found the issue has something to do with the CRS. I used the Dutch ESPG:28992 and this seems to be the problem. Using ESPG:32631 (WGS84 UTM31N) results in a mesh file! :-)

**Comment by jvdkwast** [comment]
The Dutch one should also work. Did you check if the flow direction layer from SAGA caries the projection? In recent versions of QGIS some projections are lost when using SAGA tools and have to be re-assigned after the output is created. Then it should work. For some reason the UTM projections don't have this problem. I had the problem too with the French EPSG:2154.

**Comment by etiennethomassen** [comment]
Yes the on with the Dutch projection identifies as EPSG:28922 when I drag it into QGIS. I get the error:
**Traceback (most recent call last):
File "/home/etienne/.local/share/QGIS/QGIS3/profiles/default/python/plugins/crayfish/processing/saga_flow_to_grib.py", line 155, in processAlgorithm
grib_band = grib.GetRasterBand(band_nr)
AttributeError: 'NoneType' object has no attribute 'GetRasterBand'**

When I run SAGA flow to GRIB

(Dutch AHN seems a bit to detailed to get meaningfull arrows from the mesh file though)

**Comment by DrewFrance** [comment]
Same problem as above
