### ISSUE TITLE
Add export plots to processing

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#391]
To generate time series or cross section plots, you need to use the graphical plot tool. It will be good to have a processing in Crayfish to allow generating plots from vector (e.g. points) and a quantity and export them as csv.

**Comment by saberraz** [comment]
You can also allow users to decide which column to be used for labelling of the CSV output. Currently, it uses IDs.

**Comment by PeterPetrik** [comment]
duplicate of #406
