### ISSUE TITLE
Support for exporting vector information

### ISSUE THREAD

**Issue by mostlyAtNight** [lutraconsulting/qgis-crayfish-plugin#40]
Support exporting vector (e.g. velocity) data as some kind of vector dataset

**Comment by saberraz** [comment]
Similar to raster export...ideally a way of re-sampling the vectors would be a great option

**Comment by PeterPetrik** [comment]
From Crayfish 3.x release and QGIS 3.4 release, the rendering and styling is implemented in QGIS Core. The data reading and support is implemented in [MDAL](https://github.com/lutraconsulting/MDAL/issues).
Please reopen the ticket in QGIS bug tracker for rendering issues or MDAL for format support issues. 
Thanks.
