### ISSUE TITLE
Export plots as a Processing Toolbox alg

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#406]
It will be good to have plotting as a set of processing algorithms. It will take mesh and point/line layers as input and generates CSV as output containing time series or cross section data.

**Comment by PeterPetrik** [comment]
actually it means to create processing algorithm on top of https://github.com/lutraconsulting/qgis-crayfish-plugin/blob/master/crayfish/plot.py

**Comment by jfbrz** [comment]
Hi guys, just to give you some feedback, I opted to write a script based on the plot.py. When I find the time, I might make a plug-in out of it. First I will need to figure out first the adequate writing of Python in functions.. To be clear, the script is built to export only NOAA history files (wave data), therefore not workable for other types of files.

[GribExt.py.zip](https://github.com/lutraconsulting/qgis-crayfish-plugin/files/3741227/GribExt.py.zip)
