### ISSUE TITLE
Support for all TUFLOW SMS Elements

### ISSUE THREAD

**Issue by mostlyAtNight** [lutraconsulting/qgis-crayfish-plugin#41]

**Comment by saberraz** [comment]
Information about materials, boundary conditions, etc contains within each element. It would be ideal to have a nice way of rendering the mesh, not only using the elevation, but also using those other values.

**Comment by PeterPetrik** [comment]
From Crayfish 3.x release and QGIS 3.4 release, the rendering and styling is implemented in QGIS Core. The data reading and support is implemented in [MDAL](https://github.com/lutraconsulting/MDAL/issues).
Please reopen the ticket in QGIS bug tracker for rendering issues or MDAL for format support issues. 
Thanks.
