### ISSUE TITLE
Documentation - adding Crayfish processing provider in a Python script

### ISSUE THREAD

**Issue by Brent-Edwards** [lutraconsulting/qgis-crayfish-plugin#410]
I am attempting to call the CrayfishExportRaster tool from a standalone Python script and I can't figure out how to add the Crayfish tools as a provider.

After calling `sys.path.append('/path/to/my/user/added/plugins')` I am trying to figure out how to import the CrayfishProcessingProvider and then add it to the registry:

```
from .plugin.processing import CrayfishProcessingProvider
crayfish_provider = CrayfishProcessingProvider()
QgsApplication.processingRegistry().addProvider(crayfish_provider)
```

I can't seem to get it to work.

It would be very helpful to add some documentation on how to do this.

**Comment by PeterPetrik** [comment]
could you please show the error you are getting? the code looks ok (the plugin does it in https://github.com/lutraconsulting/qgis-crayfish-plugin/blob/master/crayfish/plugin.py)

**Comment by PeterPetrik** [comment]
processing algs were moved to QGIS repository directly. Please check with the latest master and reopen in QGIS project if necessary. thanks
