### ISSUE TITLE
Feature request - Rasterize tool: output data type and nodata value options

### ISSUE THREAD

**Issue by Brent-Edwards** [lutraconsulting/qgis-crayfish-plugin#411]
The tool defaults to Float64 data type and NaN for nodata. It would be useful to provide the possibility to modify these defaults.

**Comment by saberraz** [comment]
Once it is a raster, you can do that through QGIS/GDAL tools. But I agree, it would be nice to have options to set the output data type and NULL values.

**Comment by Brent-Edwards** [comment]
> Once it is a raster, you can do that through QGIS/GDAL tools. 

Agreed. That's what I've been doing. Being able to modify data type and nodata values would avoid extra i/o and steps in my workflow.

The tool is already great and super useful! Thanks :)

**Comment by Brent-Edwards** [comment]
Please refer to the following post regarding the difficulty of dealing with NaN values in GDAL - [gis.stackexchange.com/questions/134084/replacing-nan-pixel-values-in-geotiff-using-gdal](url). I would therefore suggest defaulting to a value other than NaN.

**Comment by PeterPetrik** [comment]
Processing algorithms were moved to QGIS processing framework in QGIS repo. Please reopen the issue in the official tracker. If you want to fund the development, please contact us on info@lutraconsulting.co.uk. Thanks
