### ISSUE TITLE
[Processing] An option to load the contour intervals from a text file

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#418]

**Comment by PeterPetrik** [comment]
Currently you have 2 possibilities to specify contour levels
A) you specify minimum, maximum and interval between contour levels
B) you specify comma separated list of contour levels

When B) is present, it has priority over A)
So these 2 settings are equivalent:
![Screenshot 2020-01-10 at 14 27 35](https://user-images.githubusercontent.com/804608/72339914-7eaed400-36c7-11ea-81e0-1d0556127111.png)

![Screenshot 2020-01-10 at 14 28 08](https://user-images.githubusercontent.com/804608/72339891-7060b800-36c7-11ea-8796-c087307204d4.png)
