### ISSUE TITLE
XMDF Support

### ISSUE THREAD

**Issue by mostlyAtNight** [lutraconsulting/qgis-crayfish-plugin#42]

**Comment by mostlyAtNight** [comment]
Also consider adding support for the following:

- Basement
- Anuga
- MIKE
- Sobek

**Comment by saberraz** [comment]
Telemac support:
http://www.gdal.org/drv_selafin.html

**Comment by wonder-sk** [comment]
Basic support for XMDF added in 06ae5604c13d312f7faf7a7d0e9047968b4b1a9f (only reading of result data)
