### ISSUE TITLE
Issues Loading Goes Data

### ISSUE THREAD

**Issue by cristoph15** [lutraconsulting/qgis-crayfish-plugin#422]
With the latest qgis crayfish update, I have tried to load Goes data and it fails everytime. Wondering if I am doing something Wrong. 
[G16_C13_20170826_010055-var0.nc.zip](https://github.com/lutraconsulting/qgis-crayfish-plugin/files/4173634/G16_C13_20170826_010055-var0.nc.zip)
This is data from Hurricane Harvey.  Thanks in advance for the help!

**Comment by PeterPetrik** [comment]
<img width="753" alt="Screen Shot 2021-01-20 at 8 55 27" src="https://user-images.githubusercontent.com/804608/105144251-41acc700-5afd-11eb-925c-9416a46ab017.png">

possible to open in QGIS 3.16 without a problem
