### ISSUE TITLE
Projecting lat-lon (EPSG:4326) data on other projection not working

### ISSUE THREAD

**Issue by hcwinsemius** [lutraconsulting/qgis-crayfish-plugin#424]
Meshes are not displayed when the project CRS is set to a different one than the projection of the mesh itself.

**Comment by PeterPetrik** [comment]
this is fixed on QGIS master, can you try with the nightly build?

**Comment by saberraz** [comment]
Closing this. Please test and report in QGIS issue tracker, as this is no longer a problem related to Crayfish.
