### ISSUE TITLE
Issues with polygon contours

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#425]
Polygons generated from contour processing algorithm are not very usable. They contain lots of very tight angles, sliver polygons, self-intersecting, duplicate nodes, polygons with less than 3 nodes and small areas:

![image](https://user-images.githubusercontent.com/2649047/77290193-8eecbc00-6cd3-11ea-9b87-da7e2459ecbd.png)

**Comment by PeterPetrik** [comment]
Polygon contours algorithm is part of QGIS analysis library and processing is gone from Crayfish too. Please reopen in QGIS issue tracker if still the issue exists with the sample dataset & processing algorithm inputs to replicate. Thanks
