### ISSUE TITLE
Crayfish Flow Direction - Problem with the arrow style in the exported image

### ISSUE THREAD

**Issue by fberdes** [lutraconsulting/qgis-crayfish-plugin#426]
I am having trouble when exporting a map with the flow direction arrows: after designing the layout, the map exported doesn't respect the setted arrow parametres (length, spacing, head options, etc). Any idea how to fix it?

Crayfish Installed version | 3.2.1
QGIS version | 3.10.3-A Coruña
Windows 10

Exported image
![FlowDirection_exported image](https://user-images.githubusercontent.com/62660068/77555062-99ef4a00-6e95-11ea-8499-d4fcdbc0d82a.JPG)

Print layout
![FlowDirection_PrintLayout](https://user-images.githubusercontent.com/62660068/77555070-9b207700-6e95-11ea-999f-0a06d40955e3.JPG)

**Comment by saberraz** [comment]
Hi @fberdes 
You can change the settings for mesh vector styling to use a predefined grid for spacing:
![Screenshot_20200325_160641](https://user-images.githubusercontent.com/2649047/77558420-d2e9e780-6eb2-11ea-9bfe-bf22dad2f268.png)

Another option is to use Traces and change the Particle Counts and Max. Tail Length to get a better idea of general direction of arrows:
![Screenshot_20200325_160941](https://user-images.githubusercontent.com/2649047/77558803-4c81d580-6eb3-11ea-8876-bba1ea48d8b3.png)

**Comment by saberraz** [comment]
I am closing this ticket as this is related to QGIS styling. Feel free to ask for further help on QGIS mailing list.
