### ISSUE TITLE
Problem creating grib from SAGA flow direction result

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#430]
https://lists.osgeo.org/pipermail/qgis-user/2020-April/045340.html

![image (13)](https://user-images.githubusercontent.com/2649047/79101078-b9c0b200-7d5f-11ea-9139-f98e98a28051.png)

**Comment by PeterPetrik** [comment]
@saberraz do you have testcase for this?

**Comment by saberraz** [comment]
@PeterPetrik  it seems not to be working with any input DTM raster:
```

QGIS version: 3.15.0-Master
QGIS code revision: 850bfb23b0
Qt version: 5.12.8
GDAL version: 3.0.4
GEOS version: 3.8.0-CAPI-1.13.1 
PROJ version: Rel. 6.3.1, February 10th, 2020
Processing algorithm…
Algorithm 'SAGA Flow to GRIB' starting…
Input parameters:
{ 'CRAYFISH_INPUT_RASTER' : '/home/saber/tmp/bike_3d/srtm.tif', 'CRAYFISH_OUTPUT_GRIB' : '/tmp/test.grb' }

Traceback (most recent call last):
File "/home/saber/.local/share/QGIS/QGIS3/profiles/default/python/plugins/crayfish/processing/saga_flow_to_grib.py", line 155, in processAlgorithm
grib_band = grib.GetRasterBand(band_nr)
AttributeError: 'NoneType' object has no attribute 'GetRasterBand'

Execution failed after 38.61 seconds

Loading resulting layers
Algorithm 'SAGA Flow to GRIB' finished
```

**Comment by saberraz** [comment]
Here is a sample data:
[flowdir.zip](https://github.com/lutraconsulting/qgis-crayfish-plugin/files/5094401/flowdir.zip)

**Comment by vcloarec** [comment]
Unable to read this data with GDAL, so the processing can't work. I tried with my own data, and the processing worked without issue.

**Comment by jvdkwast** [comment]
I'm having this same error now too. I tried in QGIS 3.10.11 and 3.16.0.
It works with this dataset (30 m, EPSG: 32632):
[flowdir.zip](https://github.com/lutraconsulting/qgis-crayfish-plugin/files/5523655/flowdir.zip)

It gives the error with this dataset. Same procedure, but 5 m resolution EPSG:28992:
[flowdirection.zip](https://github.com/lutraconsulting/qgis-crayfish-plugin/files/5523569/flowdirection.zip)

I think the sample data of Aug 19 was missing one file. The files in this comment should work when dragging to QGIS.

**Comment by vcloarec** [comment]
it seems to be a projection issue with gdal/grib. when I try to manually convert :
![image](https://user-images.githubusercontent.com/7416892/101025834-7fa15c00-354c-11eb-8063-12c6ffb584e6.png)

upstream issue...

The workaround could be to  re project the data.
