### ISSUE TITLE
BASEMENT 3.0.2 morphological results

### ISSUE THREAD

**Issue by mattfack** [lutraconsulting/qgis-crayfish-plugin#434]
I am experiencing a proble in visualizing with crayfish the results of morphodynamic simulations run with basement 3.0.2.

As compared to ParaView visualization:

1. some results are missing (ns_hyd_discharge and ns_mor_discharge)
2. the other results are not as expected, i.e. not the same as what I see in ParaView (which is much more reasonable)

**Comment by saberraz** [comment]
@mattfack this is a feature request for MDAL. Crayfish no longer handles file formats. Please follow this:
https://github.com/lutraconsulting/MDAL/issues/247
