### ISSUE TITLE
Disable plots for not appropriate datasets

### ISSUE THREAD

**Issue by PeterPetrik** [lutraconsulting/qgis-crayfish-plugin#442]
- Do not allow 1D plots for 2D and 3D datasets
- Do not allow 2D plots for 1D and 3D datasets
- Do not allow 3D plots for 1D and 2D datasets

**Comment by saberraz** [comment]
Hmmmm...I can still plot 2D when I have 1D data. Tried the UGRID 1D test dataset:

![image](https://user-images.githubusercontent.com/2649047/82642245-86e2c700-9c05-11ea-9c24-d7ad45d61ac2.png)

**Comment by PeterPetrik** [comment]
- also can 1D plot get some icon (line a single colored dot?)
- also would it be possible to rename Plot to 2D Plot
- also would it be possible to sort the plots in the menu (1D, 2D, 3D)?

**Comment by vcloarec** [comment]
@saberraz , I think it is normal. The plot are available in the menu with any layer selected. You can choose the layer in the plot widget. Have you got any layer to choose in the 2D plot widget if you have only 1D mesh?

**Comment by vcloarec** [comment]
@for 1D icon, I wonder how you do usually to draw it?

**Comment by vcloarec** [comment]
New approach with layer filters :

![layer_crayfish](https://user-images.githubusercontent.com/7416892/82717880-0788de00-9c6d-11ea-928e-832b57e9d582.gif)

![layer_crayfish-2](https://user-images.githubusercontent.com/7416892/82717917-4a4ab600-9c6d-11ea-8513-eec90acdcacd.gif)

**Comment by PeterPetrik** [comment]
nice!!

**Comment by PeterPetrik** [comment]
@vcloarec i do not see any PR with these changes?

**Comment by vcloarec** [comment]
oups, sorry, I didn't see it was merged
