### ISSUE TITLE
1d plot timeseries from layer error

### ISSUE THREAD

**Issue by PeterPetrik** [lutraconsulting/qgis-crayfish-plugin#443]
When clicking-on the dropdown of ‘From layer’, the following error message appears

<img width="890" alt="Screenshot 2020-05-15 at 11 05 38" src="https://user-images.githubusercontent.com/804608/82032768-061f4a80-969c-11ea-9388-9f005c768f1b.png">

**Comment by saberraz** [comment]
I think this is related to the Debug build of QGIS nightly. The warnings should disappear in the normal release.

**Comment by vcloarec** [comment]
I can't reproduce it...

**Comment by PeterPetrik** [comment]
QGIS nightly is not debug build. Also it looks it does not come from crayfish , but some other window... 
@saberraz can you reproduce it on windows? otherwise we can maybe close it
