### ISSUE TITLE
Do not show 1D data in the processing for 2D grids

### ISSUE THREAD

**Issue by PeterPetrik** [lutraconsulting/qgis-crayfish-plugin#448]
Export mesh faces gives you the option to export a 1D layer, but nothing is created. (maybe the option to select a 1D layer should be removed?)

Export gridded value on mesh also gives you the option to export a 1D layer with all data groups (output parameters) but because you have to select a grid spacing it generates a non-functional set of points with no data. (maybe the option to select a 1D layer should be removed?)

**Comment by PeterPetrik** [comment]
also can you please check: 

Export gridded value on mesh [] result in a vector layer containing all mesh points cell centers, edges, face(centers). The vector points have no data (values).

**Comment by vcloarec** [comment]
> Export gridded value on mesh [] result in a vector layer containing all mesh points cell centers, edges, face(centers). The vector points have no data (values)

I do not understand, maybe there is a missing link

**Comment by Hubble90** [comment]
One dimension less can be one dimension more. 4D is 3D plus time dimension.

**Comment by vcloarec** [comment]
> Export gridded value on mesh [] result in a vector layer containing all mesh points cell centers, edges, face(centers). The vector points have no data (values).

I think it is NaN value when gridded value are on vertices, related with https://github.com/qgis/QGIS/pull/36852
When point are in mesh vertex, it like between severals faces, so value was NaN

**Comment by vcloarec** [comment]
> Export mesh faces gives you the option to export a 1D layer, but nothing is created. (maybe the option to select a 1D layer should be removed?)
> 
> Export gridded value on mesh also gives you the option to export a 1D layer with all data groups (output parameters) but because you have to select a grid spacing it generates a non-functional set of points with no data. (maybe the option to select a 1D layer should be removed?)

I have tried to find a way to filter mesh layer in the map layer combo box, maybe I am wrong, but not sure it is possible in the processing widget...
So I think it is difficult or too much tricky to not display 1D mesh in the combo box.

**Comment by PeterPetrik** [comment]
I think we would have to do something similar what is done for the vector layers. see https://github.com/qgis/QGIS/blob/3adbed503d5c1621d4dc8e4e217ce37835eceaae/src/core/processing/qgsprocessing.h#L44

I have created https://github.com/qgis/QGIS/issues/36920 to fix it , which is outside the scope of this project
