### ISSUE TITLE
trace animation doesn't work in crayfish 3.2.1 

### ISSUE THREAD

**Issue by Yomari99** [lutraconsulting/qgis-crayfish-plugin#458]
I am trying to create a trace animation from a netcdf file containing X and Y velocity components of surface flow (out of pluvial flooding simulation) at different time instants. When I export the trace animation, I found out that crayfish doesn't animate through all the time instants, rather it shows only my current time instant over the animation duration. My animation doesnt show gradually increasing velocity, starting with zero value at time instant 0 and then decreasing after a certain time instant, rather it remains constant, showing only my currently displayed velocity field. Is anyone else also having the same issue and how can I fix it?

I am using crayfish 3.2.1 and QGIS 3.12.3.

**Comment by PeterPetrik** [comment]
Hi @Yomari99 , can you please update to crayfish 3.4.4 and let me know if that works?
Peter
