### ISSUE TITLE
Rasterize tool: Option for treatment of border pixels

### ISSUE THREAD

**Issue by Brent-Edwards** [lutraconsulting/qgis-crayfish-plugin#460]
It would be really useful to have an option similar to the -at option in [gdal_rasterize.html](http://www.gdal.org/programs/gdal_rasterize.html) so that all pixels touched by the mesh will be processed, not just those on the line render path, or whose center point is within the mesh domain.

**Comment by PeterPetrik** [comment]
should be reopened in the QGIS issue tracker. The processing algorithm were moved to QGIS core processing algorithms, we no longer develop processing algs in the crayfish plugin.
