### ISSUE TITLE
Quiver & streamlines

### ISSUE THREAD

**Issue by huyquangt** [lutraconsulting/qgis-crayfish-plugin#466]
Hi everyone,

I am wondering if there is a chance to show quivers and streamline plots from a scatter points (e.g. from a text file with four columns: lon,lat,U,V-velocity)  using crayfish plug-in?  I know this is a very simple plot which can be easily done in Python alone, but it's good to try with crayfish if available.

 Thank you.
Huy

**Comment by PeterPetrik** [comment]
Hi, 

crayfish is used only to support plots for QGIS Mesh Layers. For such plot it is better to use dataplotly or write custom QGIS python plugin to support it.

Kind regards,
Peter
