### ISSUE TITLE
Feature request - Drape (set Z value from mesh)

### ISSUE THREAD

**Issue by Brent-Edwards** [lutraconsulting/qgis-crayfish-plugin#469]
It would be great to provide the same functionality as the QGIS core "Drape (set Z value from raster)" processing tool using a mesh as a surface instead of a raster. The "Export Gridded Value on Mesh" code could likely be adapted to enable point inputs instead of a regular grid. The QGIS core tool could also be modified to support mesh inputs.

**Comment by PeterPetrik** [comment]
should be reopened in the QGIS core processing algorithms, we no longer develop processing algs in the crayfish plugin.

**Comment by Brent-Edwards** [comment]
> should be reopened in the QGIS core processing algorithms, we no longer develop processing algs in the crayfish plugin.

Done - [https://github.com/qgis/QGIS/issues/42699](url)
