### ISSUE TITLE
SAGA to GRIB not working

### ISSUE THREAD

**Issue by DrewFrance** [lutraconsulting/qgis-crayfish-plugin#472]
QGIS version: 3.16.1-Hannover
QGIS code revision: b381a90dca
Qt version: 5.11.2
GDAL version: 3.1.4
GEOS version: 3.8.1-CAPI-1.13.3
PROJ version: Rel. 6.3.2, May 1st, 2020
Processing algorithm…
Algorithm 'SAGA Flow to GRIB' starting…
Input parameters:
{ 'CRAYFISH_INPUT_RASTER' : 'E:/SAMPLE.tif', 'CRAYFISH_OUTPUT_GRIB' : 'TEMPORARY_OUTPUT' }

Traceback (most recent call last):
File "C:/Users/mycomputer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\crayfish\processing\saga_flow_to_grib.py", line 155, in processAlgorithm
grib_band = grib.GetRasterBand(band_nr)
AttributeError: 'NoneType' object has no attribute 'GetRasterBand'

Execution failed after 71.90 seconds

Loading resulting layers
Algorithm 'SAGA Flow to GRIB' finished

**Comment by PeterPetrik** [comment]
fixed the crash by https://github.com/lutraconsulting/qgis-crayfish-plugin/pull/471
