### ISSUE TITLE
Crayfish errors when starting QGIS 2.18.9

### ISSUE THREAD

**Issue by fmaas68** [lutraconsulting/qgis-crayfish-plugin#477]
For legacy purposes I have to use QGIS 2.18.9 and when starting it I get a slew of error messages related to Crayfish:

![image](https://user-images.githubusercontent.com/79066714/107894952-57939780-6f96-11eb-83e1-1886d6fd9e49.png)
![image](https://user-images.githubusercontent.com/79066714/107894968-624e2c80-6f96-11eb-9b2b-a67a82127f87.png)
![image](https://user-images.githubusercontent.com/79066714/107894979-6b3efe00-6f96-11eb-8f48-531ab81cdfa5.png)
![image](https://user-images.githubusercontent.com/79066714/107894986-72660c00-6f96-11eb-8375-c4fffcf2714d.png)

HELP! How do I resolve these (if at all). I have never had these problems at all before.

Thanks in advance.

**Comment by PeterPetrik** [comment]
Hi, QGIS 2.x is not longer supported. The crayfish binaries are no longer on out website. We can find the old copy of the crayfish and send it to you and give you additional assistance, if you have small office support package with us https://www.lutraconsulting.co.uk/support/
Kind Regards,
Peter
