### ISSUE TITLE
Feature request: Show sum of integrals in 2D-plot

### ISSUE THREAD

**Issue by Tropiskstorm** [lutraconsulting/qgis-crayfish-plugin#480]
When plotting time series of flux-layer from a line, the integral of the values crossing the line is plotted (i.e. sum of flux at each timestep). It would be very helpful if also the sum of the integrals for the entire time series (i.e. total accumulated flux crossing the line) could be easily accessed, e.g. displayed at the bottom.

![image](https://user-images.githubusercontent.com/83702718/117134681-26ad4c80-ada6-11eb-8dbb-573adceeaac4.png)

**Comment by saberraz** [comment]
For this, you can first use "Mesh Calculator" and Sum(agg) function to generate a mesh with those values.

**Comment by Tropiskstorm** [comment]
Thanks!

**Comment by Tropiskstorm** [comment]
Thanks!
