### ISSUE TITLE
QGIS Cloud publishing problem

### ISSUE THREAD

**Issue by ARTCON2020** [lutraconsulting/qgis-crayfish-plugin#486]
An error has occurred while executing Python code: 

TypeError: 'QgsMeshLayer' object is not iterable 
Traceback (most recent call last):
  File "C:\Users/azmtas01/AppData/Roaming/QGIS/QGIS3\profiles\Flomsonekartlegging/python/plugins\qgiscloud\qgiscloudplugindialog.py", line 815, in publish_map
    elif self.check_login() and self.check_layers():
  File "C:\Users/azmtas01/AppData/Roaming/QGIS/QGIS3\profiles\Flomsonekartlegging/python/plugins\qgiscloud\qgiscloudplugindialog.py", line 918, in check_layers
    for layer in sorted(unsupported_layers[0], key=lambda layer: layer.name()):
TypeError: 'QgsMeshLayer' object is not iterable

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.22.1-Białowieża Białowieża, 663dcf8fb9 

Python Path:
C:/PROGRA~1/QGIS32~1.1/apps/qgis/./python
C:/Users/azmtas01/AppData/Roaming/QGIS/QGIS3\profiles\Flomsonekartlegging/python
C:/Users/azmtas01/AppData/Roaming/QGIS/QGIS3\profiles\Flomsonekartlegging/python/plugins
C:/PROGRA~1/QGIS32~1.1/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.22.1\bin\python39.zip
C:\PROGRA~1\QGIS32~1.1\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib
C:\Program Files\QGIS 3.22.1\bin
C:\Users\azmtas01\AppData\Roaming\Python\Python39\site-packages
C:\PROGRA~1\QGIS32~1.1\apps\Python39
C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\site-packages\GDAL-3.4.0-py3.9-win-amd64.egg
C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\site-packages\Pythonwin
C:/Users/azmtas01/AppData/Roaming/QGIS/QGIS3\profiles\Flomsonekartlegging/python
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\
C:\Users\azmtas01\AppData\Roaming\Python\Python39\site-packages\mikeio1d\bin
C:\Users/azmtas01/AppData/Roaming/QGIS/QGIS3\profiles\Flomsonekartlegging/python/plugins\qgis2web
C:\Users\azmtas01\AppData\Roaming\QGIS\QGIS3\profiles\Flomsonekartlegging\python\plugins
.
D:/QGIS

**Comment by saberraz** [comment]
Hi, could you explain the steps that lead to this error? And maybe a sample QGIS project/dataset to reproduce the issue?
