### ISSUE TITLE
All cells are shown (active) in direct-rainfall models.

### ISSUE THREAD

**Issue by mostlyAtNight** [lutraconsulting/qgis-crayfish-plugin#50]
The cell / element activity flag will likely be switched on throughout the mode during a direct rainfall simulation.  In this situation, a feature would be required to allow the user to specify a value under (or over) which pixels will not be rendered.  

This would allow only depths over a threshold (e.g. 2mm) to be visualised, making the result visualisation more useful.

**Comment by wonder-sk** [comment]
In advanced contours properties it is now (since 1.3) possible to uncheck "fill values below" to apply such threshold
