### ISSUE TITLE
AnuGA results in Crayfish

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#59]
It is not possible to view AnuGA results in Crayfish! :-)
http://sourceforge.net/projects/anuga/files/validation_data/patong-1.0/patong.sww.BASIC.tgz/download

SWW file can be opened through raster as a gdal raster (netcdf file) but it is not possible to see time variable raster.

**Comment by stoiver** [comment]
I would be interested in helping to add anuga sww format to crayfish. Could you point me to the appropriate place in the code where we might be able to add sww support.

**Comment by wonder-sk** [comment]
Thanks for the interest @stoiver 

I would suggest to start in https://github.com/lutraconsulting/qgis-crayfish-plugin/blob/master/corelib/crayfish.cpp and add code to Crayfish::loadMesh(). If the SWW reader would detect that a valid SWW file was passed, it would create and populate the Mesh object with Dataset objects (which in turn contain Output objects for each timestep).

For testing, you could use the C API of the crayfish core library or you could use the python wrapper https://github.com/lutraconsulting/qgis-crayfish-plugin/blob/master/plugin/crayfish.py - in "tools" directory in the repository there are few simple scripts that use the Python API.

Please feel free to ask if anything is not clear. There is not much developer documentation, but the code is quite simple.

**Comment by wonder-sk** [comment]
@stoiver Any testing with AnuGA data would be highly appreciated!
