### ISSUE TITLE
Output Time format

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#63]
Is it possible to change the Output Time format to only hours. Currently, it is in:
d hh:mm:ss.ss. Ideally, it should be: hh:mm:ss.ss

**Comment by mostlyAtNight** [comment]
Related to #84

**Comment by wonder-sk** [comment]
Fixed in a5ea7a5da0b134c6eb445b9d690a27bd5955547e
