### ISSUE TITLE
SMS ASCII data: vectors not read correctly

### ISSUE THREAD

**Issue by wonder-sk** [lutraconsulting/qgis-crayfish-plugin#67]
Crayfish assumes the vector data are written with 3 columns per timestep (that's the case of data written by BASEMENT - last column is ignored), but the data from SMS use just 2 columns. The values are therefore shifted and assigned to wrong nodes.

Reported by Dominik Schmid.

**Comment by Doemelti** [comment]
The plugin (correctly) reports an error now if I want to open a SMS vector file. Could the support for reading those files by any chance be completed?

**Comment by saberraz** [comment]
@Doemelti feel free to open a new ticket for the SMS vector file format. Could you also add an example file. If your data are sensitive, drop us an email with the file.
