### ISSUE TITLE
Upload fails to show anything in illuvis

### ISSUE THREAD

**Issue by mostlyAtNight** [lutraconsulting/qgis-crayfish-plugin#70]
Uploaded result is shown in illuvis as a completely transparent layer (not visible).

Steps to reproduce:

1. Load a dat/2dm result in crayfish (EPSG 27700)
2. Load an OpenLayers background (canvas is set to EPSG 3857)
3. Select a time step (e.g. maxima) from crayfish result
4. Upload to illuvis

Server-side dataset contains only nodata values.

**Comment by wonder-sk** [comment]
Fixed in f68b580a9411aa7fcd05c68833d8486ba55a26c5
