### ISSUE TITLE
Problem with 2dm when there is a gap in node numbering

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#72]
In some 2dm-files, there are gaps in the mesh node numbering, eg. 1 -2 - 4 - 5. Crayfish crashes when trying to open such files - on Windows machines,  QGIS even crashes completely. Our plugin BASEmesh offers the possibility to renumber meshes - unfortunately older meshes created with e.g. SMS still might have those gaps.
Ideally the correct numbering should be checked when opening a 2dm-file and display an error / warning message

**Comment by wonder-sk** [comment]
Fixed in 891e987faa73c8414e7824739e43c7e22a90cbdf
