### ISSUE TITLE
Ubuntu installation

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#75]
After the installation of the crayfish-plugin on Ubuntu, the plugin tries to download the binary-library automatically from your website. If the platform specifications don't fit, an error is shown. Could you to add further information to this error-message? (e.g. the required Ubuntu-version, the required sip- and pyqt-version).

**Comment by wonder-sk** [comment]
sip / pyqt is not required by the library anymore. Also, the library does not require a particular version of ubuntu anymore, it should be possible to use the compiled binary in other distributions, too.
