### ISSUE TITLE
Apply, OK, Cancel options for Advanced contour

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#77]
At the moment, the dialogs 'Advanced  Contour Options' and 'Vector Options' have no buttons. The user selects a value or changes the preferences and the changes are immediately applied. If an error was made or the result is not as expected, there is no possibility to go back or restore the default settings. What would be the estimate for integrating 'Cancel' - 'OK' - and 'Apply' - buttons in both dialogs?

**Comment by wonder-sk** [comment]
The OK / Cancel / Apply buttons were omitted intentionally, so the user has immediate feedback of the changes in appearance.

In case of errors, it would be better to have undo/redo functionality in those dialogs to make it possible to go back easily.
