### ISSUE TITLE
.2dm extent incorrect

### ISSUE THREAD

**Issue by mostlyAtNight** [lutraconsulting/qgis-crayfish-plugin#82]
When loading a .2dm file, I expect crayfish to zoom to the extent of that .2dm - but it instead zooms out much further so the .2dm is hardly visible initially.  

![ss](https://cloud.githubusercontent.com/assets/884954/6353812/6ce6cc9a-bc43-11e4-97cd-715539a3b6f4.png)

.2dm loaded into QGIS with EPSG:27700 although technically it's an area far from the UK.  

I can pass you the .2dm directly as it's large..

**Comment by mostlyAtNight** [comment]
Please note that when zooming into the .2dm, the auto-detected minimum z value is 0, making the .2dm (mostly around ~530m) look all 'red'.

**Comment by wonder-sk** [comment]
Fixed in 891e987faa73c8414e7824739e43c7e22a90cbdf
