### ISSUE TITLE
Contour and vector visualisation for different datasets

### ISSUE THREAD

**Issue by mostlyAtNight** [lutraconsulting/qgis-crayfish-plugin#85]
The user will often want to display contour visualisation for one dataset (e.g. Flow) and vector (arrow) visualisations for another dataset (e.g. Velocity).  Both datasets would of course be associated with the same model (.2dm).  

Other post-processors achieve this by loading vector datasets as two 'virtual' datasets, one contour and one vector:

![vector_and_contour](https://cloud.githubusercontent.com/assets/884954/6439351/d71b1618-c0c9-11e4-9ee5-02f89aff04de.png)

**Comment by mostlyAtNight** [comment]
I propose the displayed 'time' is synchronised across all datasets associated with a give .2dm file.

**Comment by wonder-sk** [comment]
Added in c8891c4ed5ab855d5c64b50a50fa493c3a905203 and few earlier commits
