### ISSUE TITLE
Mesh-based calculator

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#87]
Currently the only way to manipulate data is to export it as GeoTIFF. It will be handy to either add support for Raster Calculator or create a new mesh-based calculator for crayfish datasets.

**Comment by saberraz** [comment]
This is what it should look like:
http://xmswiki.com/wiki/SMS:Data_Calculator

**Comment by mach0** [comment]
And dont forget about the missing functionality to create SUM - that was one of the essential points to create a bit "more" than the usual calculator

**Comment by saberraz** [comment]
@mach0 this will be covered in #301 as an aggregate function. For example, sum(depth1@00:05:00,depth1@00:10:00) which gives you the sum of depth1 quantity between 5 and 10 hours. All expressions will be available within the data calculator interface I presume.

**Comment by PeterPetrik** [comment]
MR https://github.com/lutraconsulting/qgis-crayfish-plugin/pull/302
