### ISSUE TITLE
Add GRIB support

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#89]
It will be good to have GRIB format:
http://en.wikipedia.org/wiki/GRIB
Here are some example files:
http://www.globalmarinenet.com/grib_downloads.php

**Comment by saberraz** [comment]
The API:
https://software.ecmwf.int/wiki/display/GRIB/Home

**Comment by PeterPetrik** [comment]
http://www.wmo.int/pages/prog/www/WDM/Guides/Guide-binary-2.html
TABLE 2. PARAMETERS & UNITS
shows that by parsing of GRIB_COMMENT, we can find out which of those are vectors:

033 	u-component of wind 	m/s
034 	v-component of wind 	m/s

045 	Vertical u-component shear 	/s
046 	Vertical v-component shear 	

049 	u-component of current 	m/s
050 	v-component of current 	m/s

095 	u-component of ice drift 	m/s
096 	v-component of ice drift 	m/s

**Comment by saberraz** [comment]
commonly used formats for grib data:
.grb
.bin
.grib
.grib1
.grib2
