### ISSUE TITLE
HEC 2D file format

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#91]
The hdf5 file in HEC-RAS 2D also contains the geometry (no 2dm).
To view the content of the file (warning - it is JAVA based!)

http://www.hdfgroup.org/products/java/release/download.html

**Comment by wonder-sk** [comment]
There's another viewer for hdf5 - ViTables - based on python: http://vitables.org/

Any sample files for HEC-RAS 2D output?

**Comment by wonder-sk** [comment]
Looks like it is a custom HDF5 format, not XMDF...

**Comment by saberraz** [comment]
@PeterPetrik I will pass you some example files for Hec2D on the dropbox.
The software was released officially so will be good to have support in crayfish:
http://www.hec.usace.army.mil/software/hec-ras/downloads.aspx

**Comment by saberraz** [comment]
Here is an example of the result file:
https://www.dropbox.com/s/6jhb80sge7p8g1v/BaldEagleDamBrk.zip?dl=0
