### ISSUE TITLE
Closing unwanted quantities and reloading existing files

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#95]
When opening XMDF, it displays all the content of the file (e.g. H, Q, D, V, etc). Would be very helpful to have an option to remove quantities without closing the whole file.

**Comment by michelk** [comment]
Referencing #231, it would be additionally useful to have the dataset reloaded pressing F5. This would be helpful for currently running simulations.

**Comment by PeterPetrik** [comment]
From Crayfish 3.x release and QGIS 3.4 release, the rendering and styling is implemented in QGIS Core. The data reading and support is implemented in [MDAL](https://github.com/lutraconsulting/MDAL/issues).
Please reopen the ticket in QGIS bug tracker for rendering issues or MDAL for format support issues. 
Thanks.
