### ISSUE TITLE
Support TELEMAC file in Crayfish

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#96]
To add support for reading selafin file in Crayfish. It is already supported in GDAL:

http://www.gdal.org/drv_selafin.html

**Comment by saberraz** [comment]
@PeterPetrik here is an example file:
https://www.dropbox.com/s/fh0lttjvlor5dku/baxter_SS_hotstart.zip?dl=0

**Comment by PeterPetrik** [comment]
we need gdal 2+ for support of the format, however QGIS on ubuntu 14.04 does not have it 
http://comments.gmane.org/gmane.comp.gis.qgis.user/34919

**Comment by PeterPetrik** [comment]
The format itself is well documented and parser can be easily written to match exactly our needs:
http://www.opentelemac.org/downloads/Archive/v6p0/telemac2d_user_manual_v6p0.pdf 
[telemac-appendix3.pdf](https://github.com/lutraconsulting/qgis-crayfish-plugin/files/179895/telemac-appendix3.pdf)
